#!/usr/bin/env bash
# shellcheck shell=bash
# shellcheck disable=SC1091,SC2034,SC2317,SC2329 # sourced CLI calls test overrides dynamically
set -euo pipefail

CLI_TEST_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly CLI_TEST_SCRIPT_DIR
# shellcheck source=bupt-ec-cli.sh
source "${CLI_TEST_SCRIPT_DIR}/bupt-ec-cli.sh"

TEST_TMP="$(mktemp -d)"
chmod 0700 "${TEST_TMP}"
trap 'rm -rf -- "${TEST_TMP}"' EXIT

POSIX_MODES_SUPPORTED=true
case "$(uname -s)" in
  MINGW* | MSYS* | CYGWIN*) POSIX_MODES_SUPPORTED=false ;;
esac

# Windows-backed fixtures cannot retain exact POSIX modes. Production code keeps
# its strict checks; only this sourced suite supplies synthetic stat modes.
if [[ "${POSIX_MODES_SUPPORTED}" == "false" ]]; then
  stat() {
    if [[ "${1:-}" == "-c" && "${3:-}" == "--" ]]; then
      case "${2:-}|${4:-}" in
        "%a|${PRIVATE_ENV_FILE}")
          printf '%s\n' "${CLI_TEST_PRIVATE_MODE:-600}"
          return 0
          ;;
        "%a|${DEPLOYMENT_METADATA_FILE}")
          printf '%s\n' "${CLI_TEST_METADATA_MODE:-644}"
          return 0
          ;;
      esac
    fi
    command stat "$@"
  }
fi

fail() {
  echo "FAIL: $*" >&2
  exit 1
}

assert_eq() {
  local want="$1" got="$2" label="$3"
  [[ "${got}" == "${want}" ]] || fail "${label}: got '${got}', want '${want}'"
}

assert_contains() {
  local path="$1" text="$2" label="$3"
  grep -Fq -- "${text}" "${path}" || fail "${label}: '${text}' not found"
}

assert_not_contains() {
  local path="$1" text="$2" label="$3"
  if grep -Fq -- "${text}" "${path}"; then
    fail "${label}: unexpected '${text}'"
  fi
}

assert_path_absent() {
  local path="$1" label="$2"
  [[ ! -e "${path}" && ! -L "${path}" ]] || fail "${label}: ${path} remains"
}

assert_mode() {
  local path="$1" want="$2" label="$3" got
  [[ "${POSIX_MODES_SUPPORTED}" == "true" ]] || return
  got="$(command stat -c '%a' "${path}")"
  assert_eq "${want}" "${got}" "${label} mode"
}

MOCK_BIN="${TEST_TMP}/mock-bin"
mkdir -p "${MOCK_BIN}"

cat > "${MOCK_BIN}/curl" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

output=""
url=""
original_args="$*"
printf 'curl %s\n' "${original_args}" >> "${MOCK_CURL_LOG}"
while (( $# > 0 )); do
  case "$1" in
    --output|-o)
      output="$2"
      shift 2
      ;;
    --write-out|--connect-timeout|--max-time|--max-filesize|--max-redirs|--proto|--proto-redir|--noproxy)
      shift 2
      ;;
    -*) shift ;;
    *)
      url="$1"
      shift
      ;;
  esac
done
printf 'url %s\n' "${url}" >> "${MOCK_CURL_LOG}"
printf '%s\n' "${output}" > "${MOCK_LAST_CURL_OUTPUT}"

case "${url}" in
  *install.sh)
    if [[ "${MOCK_BOOTSTRAP_FAIL:-false}" == "true" ]]; then
      exit 22
    fi
    if [[ "${MOCK_BOOTSTRAP_EMPTY:-false}" == "true" ]]; then
      : > "${output}"
      exit 0
    fi
    cat > "${output}" <<'SCRIPT'
#!/usr/bin/env bash
# Code generated by scripts/generate-install.sh; DO NOT EDIT.
printf 'installer VERSION=%s args=%s\n' "${VERSION:-}" "$*" >> "${MOCK_INSTALLER_LOG}"
exit "${MOCK_INSTALLER_STATUS:-0}"
SCRIPT
    chmod 0700 "${output}"
    ;;
  */healthz)
    if [[ "${MOCK_HEALTH_TRANSPORT_FAIL:-false}" == "true" ]]; then
      exit 7
    fi
    printf '%s' "${MOCK_HEALTH_BODY:-{\"status\":\"ok\"}}" > "${output}"
    printf '%s' "${MOCK_HEALTH_CODE:-200}"
    ;;
  */readyz)
    if [[ "${MOCK_READY_TRANSPORT_FAIL:-false}" == "true" ]]; then
      exit 7
    fi
    printf '%s' "${MOCK_READY_BODY:-{\"status\":\"OK\",\"version\":\"v0.3.1\"}}" > "${output}"
    printf '%s' "${MOCK_READY_CODE:-200}"
    ;;
  *) exit 22 ;;
esac
EOF

cat > "${MOCK_BIN}/systemctl" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

command_name="${1:-}"
printf 'systemctl %s\n' "$*" >> "${MOCK_SYSTEMCTL_LOG}"
if [[ "${MOCK_SYSTEMCTL_FAIL:-}" == "${command_name}" ]]; then
  exit "${MOCK_SYSTEMCTL_FAIL_STATUS:-1}"
fi
case "${command_name}" in
  is-active)
    [[ -f "${MOCK_STATE_DIR}/active" ]]
    ;;
  is-enabled)
    [[ -f "${MOCK_STATE_DIR}/enabled" ]]
    ;;
  start|restart)
    : > "${MOCK_STATE_DIR}/active"
    ;;
  stop)
    rm -f -- "${MOCK_STATE_DIR}/active"
    ;;
esac
EOF

cat > "${MOCK_BIN}/journalctl" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
printf 'journalctl %s\n' "$*" >> "${MOCK_JOURNAL_LOG}"
exit "${MOCK_JOURNAL_STATUS:-0}"
EOF

chmod 0755 "${MOCK_BIN}"/*
export PATH="${MOCK_BIN}:${PATH}"

write_private_config() {
  local version="${1:-v0.3.1}"
  local mirror="${2:-}"

  mkdir -p "${CONFIG_DIR}"
  cat > "${PRIVATE_ENV_FILE}" <<EOF
RELEASE_REPO='ming-kang/BUPT_EC'
RELEASE_VERSION='${version}'
DOMAIN='classroom.example.com'
SSL_CERT='/etc/tls/fullchain.pem'
SSL_KEY='/etc/tls/privkey.pem'
JW_USERNAME='test-user'
JW_PASSWORD='private-password-secret'
JW_TOKEN='private-token-secret'
APP_ADDR='127.0.0.1:8080'
DOWNLOAD_BASE_URL='${mirror}'
LOG_CALLER=''
READYZ_DIAGNOSTICS=''
EOF
  chmod 0600 "${PRIVATE_ENV_FILE}"
}

write_public_metadata() {
  local version="${1:-v0.3.1}"
  local app_addr="${2:-127.0.0.1:8080}"

  mkdir -p "${CONFIG_DIR}"
  printf 'RELEASE_VERSION=%s\nAPP_ADDR=%s\n' "${version}" "${app_addr}" > "${DEPLOYMENT_METADATA_FILE}"
  chmod 0644 "${DEPLOYMENT_METADATA_FILE}"
}

setup_case() {
  local name="$1"
  local root="${TEST_TMP}/${name}/root"

  mkdir -p "${root}"
  configure_cli_test_root "${root}"
  clear_private_deployment_config
  clear_public_deployment_metadata
  CLI_VALIDATED_DOWNLOAD_BASE_URL=""
  unset ALLOW_INSECURE_DOWNLOAD_BASE_URL VERSION
  unset MOCK_BOOTSTRAP_FAIL MOCK_BOOTSTRAP_EMPTY MOCK_INSTALLER_STATUS MOCK_HEALTH_TRANSPORT_FAIL
  unset MOCK_READY_TRANSPORT_FAIL MOCK_SYSTEMCTL_FAIL MOCK_SYSTEMCTL_FAIL_STATUS
  export MOCK_STATE_DIR="${TEST_TMP}/${name}/state"
  export MOCK_CURL_LOG="${TEST_TMP}/${name}/curl.log"
  export MOCK_LAST_CURL_OUTPUT="${TEST_TMP}/${name}/last-output"
  export MOCK_INSTALLER_LOG="${TEST_TMP}/${name}/installer.log"
  export MOCK_SYSTEMCTL_LOG="${TEST_TMP}/${name}/systemctl.log"
  export MOCK_JOURNAL_LOG="${TEST_TMP}/${name}/journal.log"
  export MOCK_JOURNAL_STATUS=0
  export MOCK_HEALTH_CODE=200
  export MOCK_READY_CODE=200
  export MOCK_HEALTH_BODY='{"status":"ok"}'
  export MOCK_READY_BODY='{"status":"OK","version":"v0.3.1"}'
  export CLI_TEST_PRIVATE_MODE=600
  export CLI_TEST_METADATA_MODE=644
  mkdir -p "${MOCK_STATE_DIR}"
  : > "${MOCK_CURL_LOG}"
  : > "${MOCK_INSTALLER_LOG}"
  : > "${MOCK_SYSTEMCTL_LOG}"
  : > "${MOCK_JOURNAL_LOG}"
  : > "${MOCK_STATE_DIR}/active"
  : > "${MOCK_STATE_DIR}/enabled"
}

run_status() {
  local output="$1"
  shift
  local status
  set +e
  "$@" > "${output}" 2>&1
  status=$?
  set -e
  printf '%s' "${status}"
}

test_source_guard_and_parser() {
  local case_dir output status
  case_dir="${TEST_TMP}/parser"
  mkdir -p "${case_dir}"
  setup_case parser
  output="${case_dir}/output.log"
  assert_eq true "${CLI_SOURCED}" "sourced CLI guard"
  if ! CONFIG_DIR="${case_dir}/attacker" bash -c '
    source "$1"
    [[ "${CONFIG_DIR}" == "/etc/bupt-ec" && "${PRIVATE_ENV_FILE}" == "/etc/bupt-ec/bupt-ec.env" ]]
  ' _ "${CLI_TEST_SCRIPT_DIR}/bupt-ec-cli.sh"; then
    fail "production CLI accepted caller path overrides"
  fi

  status="$(run_status "${output}" bash "${CLI_TEST_SCRIPT_DIR}/bupt-ec-cli.sh")"
  assert_eq 0 "${status}" "direct no-argument help status"
  assert_contains "${output}" "Usage: bupt-ec" "direct no-argument help"
  status="$(run_status "${output}" cli_main)"
  assert_eq 0 "${status}" "no-argument help status"
  assert_contains "${output}" "Usage: bupt-ec" "no-argument help"
  status="$(run_status "${output}" cli_main --help)"
  assert_eq 0 "${status}" "long help status"
  status="$(run_status "${output}" cli_main -h extra)"
  assert_eq 2 "${status}" "extra help argument status"

  : > "${MOCK_CURL_LOG}"
  status="$(run_status "${output}" cli_main unknown)"
  assert_eq 2 "${status}" "unknown command status"
  status="$(run_status "${output}" cli_main status extra)"
  assert_eq 2 "${status}" "status extra argument status"
  status="$(run_status "${output}" cli_main update v0.3.1 extra)"
  assert_eq 2 "${status}" "update extra argument status"
  status="$(run_status "${output}" cli_main update invalid)"
  assert_eq 2 "${status}" "invalid update version status"
  status="$(run_status "${output}" cli_main update "")"
  assert_eq 2 "${status}" "empty update version status"
  status="$(run_status "${output}" cli_main logs -n 0)"
  assert_eq 2 "${status}" "invalid logs count status"
  status="$(run_status "${output}" cli_main logs -f -f)"
  assert_eq 2 "${status}" "duplicate logs follow status"
  [[ ! -s "${MOCK_CURL_LOG}" ]] || fail "parser error reached curl"
  [[ ! -s "${MOCK_SYSTEMCTL_LOG}" ]] || fail "parser error reached systemctl"
}

test_root_matrix() {
  local case_dir output status command
  case_dir="${TEST_TMP}/root-matrix"
  mkdir -p "${case_dir}"
  setup_case root-matrix
  output="${case_dir}/output.log"

  # CI normally uses a non-root runner, but the behavior suite must also stay
  # meaningful when a maintainer invokes it as root. The production guard has
  # no environment override, so exercise its success branch directly there.
  if [[ "${EUID}" -eq 0 ]]; then
    for command in update config start stop restart; do
      require_cli_root "${command}" || fail "${command} root gate rejected root"
    done
    require_cli_root config show || fail "config show root gate rejected root"
    return
  fi

  for command in \
    "update" \
    "update v0.3.1" \
    "config" \
    "config show" \
    "start" \
    "stop" \
    "restart"
  do
    # shellcheck disable=SC2206
    local -a arguments=( ${command} )
    status="$(run_status "${output}" cli_main "${arguments[@]}")"
    assert_eq 1 "${status}" "${command} non-root status"
    assert_contains "${output}" "sudo bupt-ec ${command}" "${command} sudo guidance"
  done
  [[ ! -s "${MOCK_CURL_LOG}" ]] || fail "non-root command reached curl"
  [[ ! -s "${MOCK_SYSTEMCTL_LOG}" ]] || fail "non-root command reached systemctl"
}

test_private_config_loader_and_redaction() {
  local case_dir output status frame_dir target
  case_dir="${TEST_TMP}/private-loader"
  mkdir -p "${case_dir}"
  setup_case private-loader
  write_private_config
  cat >> "${PRIVATE_ENV_FILE}" <<'EOF'
ALLOW_INSECURE_DOWNLOAD_BASE_URL=true
SKIP_CHECKSUM=1
CLI_BUILD_VERSION=mutated
EOF
  frame_dir="${case_dir}/frames"
  mkdir -p "${frame_dir}"
  mktemp() {
    if [[ "${1:-}" == "/tmp/${SERVICE_NAME}-cli-config.XXXXXX" ]]; then
      command mktemp "${frame_dir}/frame.XXXXXX"
    else
      command mktemp "$@"
    fi
  }
  load_private_deployment_config
  unset -f mktemp
  [[ -z "$(find "${frame_dir}" -mindepth 1 -print -quit)" ]] || fail "private frame cleanup"
  assert_eq ming-kang/BUPT_EC "${PRIVATE_RELEASE_REPO}" "private repository frame"
  assert_eq v0.3.1 "${PRIVATE_RELEASE_VERSION}" "private version frame"
  [[ -z "${ALLOW_INSECURE_DOWNLOAD_BASE_URL+x}" ]] || fail "private env activated insecure switch"
  assert_eq dev "${CLI_BUILD_VERSION}" "private env mutated CLI state"

  output="${case_dir}/show.log"
  show_config > "${output}"
  assert_contains "${output}" "JW_PASSWORD=***" "config show password redaction"
  assert_contains "${output}" "JW_TOKEN=***" "config show token redaction"
  assert_not_contains "${output}" "private-password-secret" "config show password disclosure"
  assert_not_contains "${output}" "private-token-secret" "config show token disclosure"

  cat > "${PRIVATE_ENV_FILE}" <<'EOF'
printf '%s\n' 'source-stdout-secret'
printf '%s\n' 'source-stderr-secret' >&2
trap 'printf "%s" "exit-trap-secret"' EXIT
EOF
  chmod 0600 "${PRIVATE_ENV_FILE}"
  output="${case_dir}/unsafe-source.log"
  mktemp() {
    if [[ "${1:-}" == "/tmp/${SERVICE_NAME}-cli-config.XXXXXX" ]]; then
      command mktemp "${frame_dir}/failure-frame.XXXXXX"
    else
      command mktemp "$@"
    fi
  }
  status="$(run_status "${output}" load_private_deployment_config)"
  unset -f mktemp
  assert_eq 1 "${status}" "unsafe private source status"
  [[ -z "$(find "${frame_dir}" -mindepth 1 -print -quit)" ]] || fail "unsafe private frame cleanup"
  assert_contains "${output}" "Failed to load existing configuration safely." "unsafe private source error"
  assert_not_contains "${output}" "source-stdout-secret" "source stdout redaction"
  assert_not_contains "${output}" "source-stderr-secret" "source stderr redaction"
  assert_not_contains "${output}" "exit-trap-secret" "source trap redaction"

  write_private_config
  if [[ "${POSIX_MODES_SUPPORTED}" == "true" ]]; then
    chmod 0644 "${PRIVATE_ENV_FILE}"
  else
    CLI_TEST_PRIVATE_MODE=644
  fi
  output="${case_dir}/unsafe-mode.log"
  status="$(run_status "${output}" load_private_deployment_config)"
  assert_eq 1 "${status}" "unsafe private mode status"
  assert_not_contains "${output}" "private-password-secret" "unsafe private mode redaction"

  CLI_TEST_PRIVATE_MODE=600
  write_private_config
  CLI_EXPECTED_UID=$((EUID + 1))
  output="${case_dir}/unsafe-owner.log"
  status="$(run_status "${output}" load_private_deployment_config)"
  assert_eq 1 "${status}" "unsafe private owner status"
  assert_not_contains "${output}" "private-token-secret" "unsafe private owner redaction"
  CLI_EXPECTED_UID="${EUID}"

  if [[ "${POSIX_MODES_SUPPORTED}" == "true" ]]; then
    target="${case_dir}/private-target"
    write_private_config
    cp "${PRIVATE_ENV_FILE}" "${target}"
    rm -f -- "${PRIVATE_ENV_FILE}"
    ln -s "${target}" "${PRIVATE_ENV_FILE}"
    output="${case_dir}/private-symlink.log"
    status="$(run_status "${output}" load_private_deployment_config)"
    assert_eq 1 "${status}" "private symlink status"
    assert_not_contains "${output}" "private-password-secret" "private symlink redaction"

    rm -f -- "${PRIVATE_ENV_FILE}"
    write_private_config
    chmod 0777 "${CONFIG_DIR}"
    output="${case_dir}/private-parent.log"
    status="$(run_status "${output}" load_private_deployment_config)"
    assert_eq 1 "${status}" "writable private parent status"
    chmod 0755 "${CONFIG_DIR}"
  fi

  # A sourced test shell can carry readonly variables into the isolated child.
  # The loader must reject rather than framing a caller value if it cannot
  # clear the fixed registry first.
  write_private_config
  readonly RELEASE_REPO="caller-private-repository"
  output="${case_dir}/readonly-inherited.log"
  status="$(run_status "${output}" load_private_deployment_config)"
  assert_eq 1 "${status}" "readonly inherited registry status"
  assert_not_contains "${output}" "caller-private-repository" "readonly registry redaction"
}

test_config_show_multiline_redaction() {
  local case_dir output
  case_dir="${TEST_TMP}/config-show"
  mkdir -p "${case_dir}"
  setup_case config-show
  write_private_config
  cat >> "${PRIVATE_ENV_FILE}" <<'EOF'
JW_PASSWORD=$'line-one-password\nline-two-password'
JW_TOKEN=$'line-one-token\nline-two-token'
UNKNOWN_FIELD='must not display'
EOF
  output="${case_dir}/output.log"
  show_config > "${output}"
  assert_contains "${output}" "JW_PASSWORD=***" "multiline password redaction"
  assert_contains "${output}" "JW_TOKEN=***" "multiline token redaction"
  assert_not_contains "${output}" "line-one-password" "multiline password first line disclosure"
  assert_not_contains "${output}" "line-two-password" "multiline password continuation disclosure"
  assert_not_contains "${output}" "line-one-token" "multiline token first line disclosure"
  assert_not_contains "${output}" "line-two-token" "multiline token continuation disclosure"
  assert_not_contains "${output}" "UNKNOWN_FIELD" "unknown field disclosure"
}

test_public_metadata_loader() {
  local case_dir output status
  case_dir="${TEST_TMP}/public-metadata"
  mkdir -p "${case_dir}"
  setup_case public-metadata
  write_private_config
  write_public_metadata v0.3.1 '[::1]:8080'
  load_public_deployment_metadata
  assert_eq v0.3.1 "${PUBLIC_RELEASE_VERSION}" "metadata version"
  assert_eq '[::1]:8080' "${PUBLIC_APP_ADDR}" "metadata address"

  printf 'APP_ADDR=127.0.0.1:8080\nRELEASE_VERSION=v0.3.1\n' > "${DEPLOYMENT_METADATA_FILE}"
  chmod 0644 "${DEPLOYMENT_METADATA_FILE}"
  output="${case_dir}/bad-order.log"
  status="$(run_status "${output}" load_public_deployment_metadata)"
  assert_eq 1 "${status}" "metadata order status"
  assert_contains "${output}" "Failed to load public deployment metadata safely." "metadata order error"

  write_public_metadata
  printf 'EXTRA=value\n' >> "${DEPLOYMENT_METADATA_FILE}"
  output="${case_dir}/extra.log"
  status="$(run_status "${output}" load_public_deployment_metadata)"
  assert_eq 1 "${status}" "metadata extra record status"

  write_public_metadata v0.3.1 '127.0.0.1:8080'
  if [[ "${POSIX_MODES_SUPPORTED}" == "true" ]]; then
    chmod 0600 "${DEPLOYMENT_METADATA_FILE}"
  else
    CLI_TEST_METADATA_MODE=600
  fi
  output="${case_dir}/unsafe-mode.log"
  status="$(run_status "${output}" load_public_deployment_metadata)"
  assert_eq 1 "${status}" "metadata unsafe mode status"

  CLI_TEST_METADATA_MODE=644
  write_public_metadata
  CLI_EXPECTED_UID=$((EUID + 1))
  output="${case_dir}/unsafe-owner.log"
  status="$(run_status "${output}" load_public_deployment_metadata)"
  assert_eq 1 "${status}" "metadata unsafe owner status"
  CLI_EXPECTED_UID="${EUID}"
  if [[ "${POSIX_MODES_SUPPORTED}" == "true" ]]; then
    local metadata_target="${case_dir}/metadata-target"
    cp "${DEPLOYMENT_METADATA_FILE}" "${metadata_target}"
    rm -f -- "${DEPLOYMENT_METADATA_FILE}"
    ln -s "${metadata_target}" "${DEPLOYMENT_METADATA_FILE}"
    output="${case_dir}/metadata-symlink.log"
    status="$(run_status "${output}" load_public_deployment_metadata)"
    assert_eq 1 "${status}" "metadata symlink status"
    rm -f -- "${DEPLOYMENT_METADATA_FILE}"
    write_public_metadata
    chmod 0777 "${CONFIG_DIR}"
    output="${case_dir}/metadata-parent.log"
    status="$(run_status "${output}" load_public_deployment_metadata)"
    assert_eq 1 "${status}" "writable metadata parent status"
    chmod 0755 "${CONFIG_DIR}"
  fi

  write_public_metadata
  printf 'RELEASE_VERSION=v0.3.1\0\nAPP_ADDR=127.0.0.1:8080\n' > "${DEPLOYMENT_METADATA_FILE}"
  output="${case_dir}/nul.log"
  status="$(run_status "${output}" load_public_deployment_metadata)"
  assert_eq 1 "${status}" "metadata NUL framing status"

  write_public_metadata
  rm -f -- "${DEPLOYMENT_METADATA_FILE}"
  : > "${MOCK_CURL_LOG}"
  output="${case_dir}/no-fallback.log"
  status="$(run_status "${output}" show_health)"
  assert_eq 1 "${status}" "missing metadata health status"
  [[ ! -s "${MOCK_CURL_LOG}" ]] || fail "health fell back to private config"
}

test_status_health_and_version_semantics() {
  local case_dir output status
  case_dir="${TEST_TMP}/probe-semantics"
  mkdir -p "${case_dir}"
  setup_case probe-semantics
  write_public_metadata latest '127.0.0.1:8080'
  output="${case_dir}/health.log"

  status="$(run_status "${output}" show_health)"
  assert_eq 0 "${status}" "healthy health status"
  assert_contains "${MOCK_CURL_LOG}" "--disable" "probe ignores caller curl config"
  assert_contains "${MOCK_CURL_LOG}" "--noproxy *" "probe disables proxies"
  assert_contains "${MOCK_CURL_LOG}" "--max-redirs 0" "probe blocks redirects"
  assert_not_contains "${MOCK_CURL_LOG}" " -L" "probe does not follow redirects"
  assert_contains "${output}" "/healthz: HTTP 200 (ok)" "healthy health output"
  status="$(run_status "${output}" show_status)"
  assert_eq 0 "${status}" "healthy status command"
  assert_contains "${output}" "Configured selector: latest" "status selector"
  assert_contains "${output}" "Running version: v0.3.1" "status running version"
  status="$(run_status "${output}" show_version)"
  assert_eq 0 "${status}" "healthy version command"
  assert_contains "${output}" "CLI version: dev" "version CLI marker"
  assert_contains "${MOCK_CURL_LOG}" "url http://127.0.0.1:8080/readyz" "ready probe URL"

  export MOCK_READY_CODE=503
  export MOCK_READY_BODY='{"status":"Service Unavailable","version":"v0.3.1"}'
  output="${case_dir}/ready-503.log"
  status="$(run_status "${output}" show_health)"
  assert_eq 1 "${status}" "readiness 503 health status"
  assert_contains "${output}" "degraded/not ready" "readiness 503 health output"
  status="$(run_status "${output}" show_status)"
  assert_eq 1 "${status}" "readiness 503 status command"
  status="$(run_status "${output}" show_version)"
  assert_eq 0 "${status}" "readiness 503 version command"
  assert_contains "${output}" "Running version: v0.3.1" "503 running version"
  export MOCK_READY_BODY='{"status":"OK","version":"v0.3.1"}'
  status="$(run_status "${output}" show_version)"
  assert_eq 1 "${status}" "mismatched 503 ready body version status"

  export MOCK_READY_CODE=200
  export MOCK_READY_BODY='{"status":"OK","version":"v0.3.1"}'
  rm -f -- "${MOCK_STATE_DIR}/active"
  output="${case_dir}/inactive.log"
  status="$(run_status "${output}" show_status)"
  assert_eq 1 "${status}" "inactive status command"
  assert_contains "${output}" "Service: inactive" "inactive status output"

  : > "${MOCK_STATE_DIR}/active"
  export MOCK_READY_BODY='{"status":"OK"}'
  output="${case_dir}/malformed.log"
  status="$(run_status "${output}" show_version)"
  assert_eq 1 "${status}" "malformed ready body version status"
  assert_contains "${output}" "Running version: unavailable" "malformed ready body output"
}

test_logs_and_controls() {
  local case_dir output status
  case_dir="${TEST_TMP}/logs-controls"
  mkdir -p "${case_dir}"
  setup_case logs-controls
  output="${case_dir}/logs.log"

  status="$(run_status "${output}" show_logs)"
  assert_eq 0 "${status}" "default logs status"
  assert_contains "${MOCK_JOURNAL_LOG}" "journalctl -u bupt-ec -n 50" "default logs args"
  : > "${MOCK_JOURNAL_LOG}"
  status="$(run_status "${output}" show_logs -f -n 20)"
  assert_eq 0 "${status}" "combined logs status"
  assert_contains "${MOCK_JOURNAL_LOG}" "journalctl -u bupt-ec -n 20 -f" "combined logs args"
  export MOCK_JOURNAL_STATUS=7
  status="$(run_status "${output}" show_logs -n 5)"
  assert_eq 7 "${status}" "journal failure propagation"
  : > "${MOCK_JOURNAL_LOG}"
  status="$(run_status "${output}" show_logs -n 5 -n 6)"
  assert_eq 2 "${status}" "duplicate logs count status"
  [[ ! -s "${MOCK_JOURNAL_LOG}" ]] || fail "invalid logs args reached journalctl"

  require_cli_root() { return 0; }
  output="${case_dir}/control.log"
  status="$(run_status "${output}" cli_main stop)"
  assert_eq 0 "${status}" "stop status"
  assert_contains "${output}" "Service after stop: inactive" "stop active output"
  status="$(run_status "${output}" cli_main start)"
  assert_eq 0 "${status}" "start status"
  assert_contains "${output}" "Service after start: active" "start active output"
  export MOCK_SYSTEMCTL_FAIL=restart
  export MOCK_SYSTEMCTL_FAIL_STATUS=9
  status="$(run_status "${output}" cli_main restart)"
  assert_eq 9 "${status}" "control failure propagation"
}

test_update_bootstrap_and_floor() {
  local case_dir output status installer_path
  case_dir="${TEST_TMP}/update-bootstrap"
  mkdir -p "${case_dir}"
  setup_case update-bootstrap
  write_private_config v0.3.1
  require_cli_root() { return 0; }
  require_cli_tty() { fail "update unexpectedly touched the TTY"; }
  output="${case_dir}/output.log"

  status="$(run_status "${output}" cli_main update)"
  assert_eq 0 "${status}" "saved-selector update status"
  assert_contains "${MOCK_CURL_LOG}" "url https://github.com/ming-kang/BUPT_EC/releases/latest/download/install.sh" "official current installer URL"
  assert_contains "${MOCK_CURL_LOG}" "--disable" "Installer bootstrap ignores caller curl config"
  assert_contains "${MOCK_CURL_LOG}" "--proto =https --proto-redir =https" "official Installer protocol policy"
  assert_contains "${MOCK_INSTALLER_LOG}" "installer VERSION=v0.3.1 args=--mode=update" "saved selector passed to installer"
  installer_path="$(< "${MOCK_LAST_CURL_OUTPUT}")"
  assert_path_absent "$(dirname "${installer_path}")" "bootstrap session cleanup"

  : > "${MOCK_CURL_LOG}"
  : > "${MOCK_INSTALLER_LOG}"
  status="$(run_status "${output}" cli_main update v0.3.2)"
  assert_eq 0 "${status}" "explicit update status"
  assert_contains "${MOCK_INSTALLER_LOG}" "installer VERSION=v0.3.2 args=--mode=update" "explicit selector precedence"

  export MOCK_INSTALLER_STATUS=17
  status="$(run_status "${output}" cli_main update v0.3.2)"
  assert_eq 17 "${status}" "Installer child status propagation"
  installer_path="$(< "${MOCK_LAST_CURL_OUTPUT}")"
  assert_path_absent "$(dirname "${installer_path}")" "failed Installer session cleanup"
  unset MOCK_INSTALLER_STATUS

  export MOCK_BOOTSTRAP_FAIL=true
  status="$(run_status "${output}" cli_main update v0.3.2)"
  assert_eq 1 "${status}" "bootstrap failure status"
  installer_path="$(< "${MOCK_LAST_CURL_OUTPUT}")"
  assert_path_absent "$(dirname "${installer_path}")" "failed bootstrap session cleanup"
  unset MOCK_BOOTSTRAP_FAIL

  export MOCK_BOOTSTRAP_EMPTY=true
  status="$(run_status "${output}" cli_main update v0.3.2)"
  assert_eq 1 "${status}" "empty bootstrap asset status"
  installer_path="$(< "${MOCK_LAST_CURL_OUTPUT}")"
  assert_path_absent "$(dirname "${installer_path}")" "empty bootstrap session cleanup"
  unset MOCK_BOOTSTRAP_EMPTY

  : > "${MOCK_CURL_LOG}"
  status="$(run_status "${output}" cli_main update v0.2.0)"
  assert_eq 1 "${status}" "legacy target status"
  assert_contains "${output}" "current/latest Installer fallback" "legacy fallback guidance"
  [[ ! -s "${MOCK_CURL_LOG}" ]] || fail "legacy CLI update reached curl"

  setup_case legacy-without-config
  require_cli_root() { return 0; }
  output="${TEST_TMP}/update-bootstrap/legacy-without-config.log"
  status="$(run_status "${output}" cli_main update v0.2.0)"
  assert_eq 1 "${status}" "legacy target without config status"
  assert_contains "${output}" "current/latest Installer fallback" "legacy target without config fallback"
  [[ ! -s "${MOCK_CURL_LOG}" ]] || fail "legacy target without config reached curl"

  setup_case legacy-before-mirror
  write_private_config v0.3.1 'https://user:secret@mirror.example/releases'
  require_cli_root() { return 0; }
  output="${TEST_TMP}/update-bootstrap/legacy-before-mirror.log"
  status="$(run_status "${output}" cli_main update v0.2.0)"
  assert_eq 1 "${status}" "legacy target precedes mirror validation"
  assert_contains "${output}" "current/latest Installer fallback" "legacy target fallback before mirror validation"
  [[ ! -s "${MOCK_CURL_LOG}" ]] || fail "legacy target with invalid mirror reached curl"
}

test_mirror_bootstrap_and_reconfigure() {
  local case_dir output status
  case_dir="${TEST_TMP}/mirror-bootstrap"
  mkdir -p "${case_dir}"
  setup_case mirror-bootstrap
  write_private_config v0.3.1 'https://mirror.example/releases/'
  require_cli_root() { return 0; }
  output="${case_dir}/output.log"

  status="$(run_status "${output}" cli_main update)"
  assert_eq 0 "${status}" "HTTPS mirror update status"
  assert_contains "${MOCK_CURL_LOG}" "url https://mirror.example/releases/install.sh" "mirror installer URL"
  assert_not_contains "${MOCK_CURL_LOG}" "github.com" "mirror does not fall back to GitHub"

  setup_case http-mirror
  write_private_config v0.3.1 'http://mirror.example/releases'
  require_cli_root() { return 0; }
  output="${TEST_TMP}/mirror-bootstrap/http.log"
  status="$(run_status "${output}" cli_main update)"
  assert_eq 1 "${status}" "HTTP mirror without opt-in status"
  [[ ! -s "${MOCK_CURL_LOG}" ]] || fail "HTTP mirror without opt-in reached curl"
  export ALLOW_INSECURE_DOWNLOAD_BASE_URL=true
  status="$(run_status "${output}" cli_main update)"
  assert_eq 0 "${status}" "HTTP mirror exact opt-in status"
  assert_contains "${MOCK_CURL_LOG}" "url http://mirror.example/releases/install.sh" "HTTP mirror URL"
  assert_contains "${MOCK_CURL_LOG}" "--proto =http,https --proto-redir =http,https" "HTTP mirror protocol policy"

  setup_case reconfigure
  write_private_config v0.3.1
  require_cli_root() { return 0; }
  private_load_marker="${TEST_TMP}/mirror-bootstrap/private-load-ran"
  printf ': > %q\n' "${private_load_marker}" >> "${PRIVATE_ENV_FILE}"
  require_cli_tty() { return 1; }
  output="${TEST_TMP}/mirror-bootstrap/reconfigure-no-tty.log"
  status="$(run_status "${output}" cli_main config)"
  assert_eq 1 "${status}" "reconfigure TTY status"
  assert_path_absent "${private_load_marker}" "reconfigure TTY gate private load"
  [[ ! -s "${MOCK_CURL_LOG}" ]] || fail "reconfigure reached network before TTY check"

  require_cli_tty() { return 0; }
  VERSION=v9.9.9
  export VERSION
  status="$(run_status "${output}" cli_main config)"
  assert_eq 0 "${status}" "reconfigure bootstrap status"
  assert_contains "${MOCK_INSTALLER_LOG}" "installer VERSION= args=--mode=reconfigure" "reconfigure preserves selector"
}

test_bootstrap_url_redaction() {
  local case_dir output status
  case_dir="${TEST_TMP}/bootstrap-redaction"
  mkdir -p "${case_dir}"
  setup_case bootstrap-redaction
  write_private_config v0.3.1 'https://user:mirror-password@mirror.example/releases?token=mirror-token'
  require_cli_root() { return 0; }
  output="${case_dir}/output.log"
  status="$(run_status "${output}" cli_main update)"
  assert_eq 1 "${status}" "invalid mirror status"
  assert_not_contains "${output}" "mirror-password" "mirror password redaction"
  assert_not_contains "${output}" "mirror-token" "mirror token redaction"
  [[ ! -s "${MOCK_CURL_LOG}" ]] || fail "invalid mirror reached curl"

  setup_case invalid-ipv6-mirror
  write_private_config v0.3.1 'https://[::::]/releases'
  require_cli_root() { return 0; }
  output="${TEST_TMP}/bootstrap-redaction/invalid-ipv6.log"
  status="$(run_status "${output}" cli_main update)"
  assert_eq 1 "${status}" "invalid IPv6 mirror status"
  [[ ! -s "${MOCK_CURL_LOG}" ]] || fail "invalid IPv6 mirror reached curl"
}

run_suite() {
  local test_name
  local -a tests=(
    test_source_guard_and_parser
    test_root_matrix
    test_private_config_loader_and_redaction
    test_config_show_multiline_redaction
    test_public_metadata_loader
    test_status_health_and_version_semantics
    test_logs_and_controls
    test_update_bootstrap_and_floor
    test_mirror_bootstrap_and_reconfigure
    test_bootstrap_url_redaction
  )

  printf 'Running CLI behavior suite (%d scenarios)...\n' "${#tests[@]}"
  for test_name in "${tests[@]}"; do
    ( "${test_name}" )
  done
}

run_suite
printf 'CLI behavior tests passed (10 scenarios).\n'
