#!/usr/bin/env bash
# shellcheck shell=bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT="${SCRIPT_DIR}/install.sh"
readonly SCRIPT_DIR OUTPUT

# This explicit list is the installer source order. Do not replace it with a
# glob or directory traversal: release assets must be deterministic everywhere.
INSTALLER_FRAGMENTS=(
  "installer/00-preamble.sh"
  "installer/10-config.sh"
  "installer/20-release.sh"
  "installer/30-render.sh"
  "installer/40-transaction.sh"
  "installer/50-main.sh"
)
readonly INSTALLER_FRAGMENTS

usage() {
  echo "Usage: $0 [--check]" >&2
}

check_only=false
case "$#" in
  0)
    ;;
  1)
    if [[ "$1" != "--check" ]]; then
      usage
      exit 2
    fi
    check_only=true
    ;;
  *)
    usage
    exit 2
    ;;
esac

candidate="$(mktemp "${SCRIPT_DIR}/.install.sh.tmp.XXXXXX")"
cleanup() {
  rm -f -- "${candidate}"
}
trap cleanup EXIT

{
  printf '%s\n' '#!/usr/bin/env bash'
  printf '%s\n' '# Code generated by scripts/generate-install.sh; DO NOT EDIT.'
  printf '%s\n' 'set -euo pipefail'
  printf '\n'
  first_fragment=true
  for fragment in "${INSTALLER_FRAGMENTS[@]}"; do
    if [[ "${first_fragment}" != "true" ]]; then
      printf '\n'
    fi
    cat "${SCRIPT_DIR}/${fragment}"
    first_fragment=false
  done
} > "${candidate}"
chmod 0755 "${candidate}"

if [[ "${check_only}" == "true" ]]; then
  # Content and executable mode are both part of the tracked release artifact.
  # On a platform with core.filemode=false, stage the mode explicitly with:
  # git add --chmod=+x scripts/install.sh
  if [[ ! -x "${OUTPUT}" ]] || ! cmp -s "${candidate}" "${OUTPUT}"; then
    echo "scripts/install.sh is out of date; run: bash scripts/generate-install.sh" >&2
    exit 1
  fi
  exit 0
fi

mv -f -- "${candidate}" "${OUTPUT}"
