#!/usr/bin/env bash
# Code generated by scripts/generate-install.sh; DO NOT EDIT.
set -euo pipefail

# shellcheck shell=bash
# shellcheck disable=SC2034

SERVICE_NAME="bupt-ec"
DEFAULT_REPO="ming-kang/BUPT_EC"
GITHUB_HOST="github.com"
INSTALL_DIR="/opt/bupt-ec"
CONFIG_DIR="/etc/bupt-ec"
ENV_FILE="${CONFIG_DIR}/bupt-ec.env"
# Installed configuration is trusted only when root owns this exact file.
# configure_installer_test_root changes this test seam for portable fixtures.
ENV_FILE_EXPECTED_UID=0
SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}.service"
SYSTEMD_ENABLED_LINK="/etc/systemd/system/multi-user.target.wants/${SERVICE_NAME}.service"
NGINX_SITE="/etc/nginx/sites-available/${SERVICE_NAME}.conf"
NGINX_ENABLED="/etc/nginx/sites-enabled/${SERVICE_NAME}.conf"
APP_USER="bupt-ec"
APP_GROUP="bupt-ec"
DEFAULT_APP_ADDR="127.0.0.1:8080"
TTY="/dev/tty"

# This is the complete persisted deployment contract. Runtime-only controls
# (for example SKIP_CHECKSUM) deliberately do not appear here.
DEPLOYMENT_CONFIG_KEYS=(
  RELEASE_REPO RELEASE_VERSION DOMAIN SSL_CERT SSL_KEY
  JW_USERNAME JW_PASSWORD JW_TOKEN APP_ADDR DOWNLOAD_BASE_URL
  LOG_CALLER READYZ_DIAGNOSTICS
)
readonly DEPLOYMENT_CONFIG_KEYS

INSTALLER_MODE="install"

INSTALLER_TMP_DIR=""
TRANSACTION_ACTIVE=false
TRANSACTION_BACKUP_DIR=""

# Captured at top-level load time. Inside functions, stdin-fed scripts report a
# fake BASH_SOURCE[0] (e.g. "main"), so entrypoint detection must not run there.
# - ./install.sh or curl|bash: not sourced → run main
# - source install.sh (unit tests): sourced → skip main
# Under `set -u`, BASH_SOURCE[0] is unbound for scripts fed on stdin — use :- .
INSTALLER_SOURCED=false
if [[ -n "${BASH_SOURCE[0]:-}" && "${BASH_SOURCE[0]}" != "$0" ]]; then
  INSTALLER_SOURCED=true
fi

# Tests source this script and call this explicit helper. Production main never
# reads a path override from the environment, so normal installer execution
# always targets the fixed /opt and /etc locations above.
configure_installer_test_root() {
  local root="$1"
  if [[ "${INSTALLER_SOURCED}" != "true" ]]; then
    echo "configure_installer_test_root is only available when install.sh is sourced." >&2
    return 1
  fi
  if [[ "${root}" != /* ]]; then
    echo "Installer test root must be absolute: ${root}" >&2
    return 1
  fi

  INSTALL_DIR="${root}/opt/bupt-ec"
  CONFIG_DIR="${root}/etc/bupt-ec"
  ENV_FILE="${CONFIG_DIR}/bupt-ec.env"
  # Test fixtures are owned by the invoking test user rather than root.
  ENV_FILE_EXPECTED_UID="${EUID}"
  SERVICE_FILE="${root}/etc/systemd/system/${SERVICE_NAME}.service"
  SYSTEMD_ENABLED_LINK="${root}/etc/systemd/system/multi-user.target.wants/${SERVICE_NAME}.service"
  NGINX_SITE="${root}/etc/nginx/sites-available/${SERVICE_NAME}.conf"
  NGINX_ENABLED="${root}/etc/nginx/sites-enabled/${SERVICE_NAME}.conf"
}

# shellcheck shell=bash
# shellcheck disable=SC2034

installer_usage() {
  echo "Usage: install.sh [--mode=install|update|reconfigure]" >&2
}

parse_mode() {
  local mode=""
  local seen_mode=false

  INSTALLER_MODE="install"
  while (( $# > 0 )); do
    case "$1" in
      --mode=*)
        if [[ "${seen_mode}" == "true" ]]; then
          echo "--mode may only be specified once." >&2
          installer_usage
          return 2
        fi
        mode="${1#--mode=}"
        if [[ -z "${mode}" ]]; then
          echo "--mode requires a value." >&2
          installer_usage
          return 2
        fi
        seen_mode=true
        ;;
      --mode)
        if [[ "${seen_mode}" == "true" ]]; then
          echo "--mode may only be specified once." >&2
          installer_usage
          return 2
        fi
        if (( $# < 2 )) || [[ -z "${2}" || "${2}" == --* ]]; then
          echo "--mode requires a value." >&2
          installer_usage
          return 2
        fi
        mode="$2"
        seen_mode=true
        shift
        ;;
      *)
        echo "Unexpected installer argument." >&2
        installer_usage
        return 2
        ;;
    esac
    shift
  done

  if [[ "${seen_mode}" == "false" ]]; then
    return 0
  fi

  case "${mode}" in
    install | update | reconfigure)
      INSTALLER_MODE="${mode}"
      ;;
    *)
      echo "--mode must be install, update, or reconfigure." >&2
      installer_usage
      return 2
      ;;
  esac
}

require_root_environment() {
  if [[ "${EUID}" -ne 0 ]]; then
    echo "This installer must run as root. Use: curl -fsSL <url> | sudo bash" >&2
    return 1
  fi
}

require_interactive_tty() {
  # A readable /dev/tty device node can still be unopenable when the process
  # has no controlling terminal; probe the actual open before any prompt.
  if [[ ! -r "${TTY}" ]] || ! : < "${TTY}" 2>/dev/null; then
    echo "Interactive input requires a TTY." >&2
    return 1
  fi
}

reset_config_state() {
  local key

  for key in "${DEPLOYMENT_CONFIG_KEYS[@]}"; do
    printf -v "CURRENT_${key}" '%s' ""
    printf -v "OVERRIDE_${key}" '%s' ""
    printf -v "OVERRIDE_${key}_SET" '%s' "false"
    printf -v "CFG_${key}" '%s' ""
  done
  OVERRIDE_VERSION=""
  OVERRIDE_VERSION_SET=false
  VALIDATED_DOWNLOAD_BASE_URL=""
  INSTALLER_MODE="install"
}

clear_current_config() {
  local key
  for key in "${DEPLOYMENT_CONFIG_KEYS[@]}"; do
    printf -v "CURRENT_${key}" '%s' ""
  done
}

clear_invocation_overrides() {
  local key
  for key in "${DEPLOYMENT_CONFIG_KEYS[@]}"; do
    printf -v "OVERRIDE_${key}" '%s' ""
    printf -v "OVERRIDE_${key}_SET" '%s' "false"
  done
  OVERRIDE_VERSION=""
  OVERRIDE_VERSION_SET=false
}

capture_config_override() {
  local key="$1"
  local source_name="$2"

  if [[ -v "${source_name}" ]]; then
    printf -v "OVERRIDE_${key}" '%s' "${!source_name}"
    printf -v "OVERRIDE_${key}_SET" '%s' "true"
  fi
}

# Snapshot invocation values before reading the installed env. Explicitly set
# empty values are retained through the paired *_SET flags.
capture_invocation_overrides() {
  local key

  clear_invocation_overrides
  for key in "${DEPLOYMENT_CONFIG_KEYS[@]}"; do
    # RELEASE_VERSION is saved deployment metadata, not an invocation input.
    # VERSION is the sole explicit release-selection override.
    if [[ "${key}" != "RELEASE_VERSION" ]]; then
      capture_config_override "${key}" "${key}"
    fi
  done

  # Keep the original command interface while storing canonical release
  # metadata. A canonical RELEASE_REPO beats the legacy REPO alias when both
  # are explicitly present.
  if [[ "${OVERRIDE_RELEASE_REPO_SET}" != "true" ]]; then
    capture_config_override RELEASE_REPO REPO
  fi

  # VERSION is a one-shot release-selection override, not persisted config.
  if [[ -v VERSION ]]; then
    OVERRIDE_VERSION="${VERSION}"
    OVERRIDE_VERSION_SET=true
  fi
}

discard_current_config_snapshot() {
  local snapshot="$1"

  if [[ -n "${snapshot}" ]]; then
    rm -f -- "${snapshot}" >/dev/null 2>&1
  fi
}

report_current_config_load_failure() {
  local snapshot="${1:-}"

  clear_current_config
  if ! discard_current_config_snapshot "${snapshot}"; then
    echo "Failed to remove temporary configuration snapshot." >&2
  fi
  # Never include an env path value or sourced output here: either can expose
  # credentials from a malformed file.
  echo "Failed to load existing configuration safely." >&2
}

# Read exactly the expected key/value NUL frames from stdin. A final read is
# deliberately required to reach EOF so source output and any trailing bytes
# cannot be silently accepted.
read_current_config_snapshot() {
  local key loaded_key value trailing=""

  for key in "${DEPLOYMENT_CONFIG_KEYS[@]}"; do
    if ! IFS= read -r -d '' loaded_key; then
      return 1
    fi
    if [[ "${loaded_key}" != "${key}" ]]; then
      return 1
    fi
    if ! IFS= read -r -d '' value; then
      return 1
    fi
    printf -v "CURRENT_${key}" '%s' "${value}"
  done

  trailing=""
  if IFS= read -r -d '' trailing; then
    return 1
  fi
  [[ -z "${trailing}" ]]
}

validate_config_directory_security() {
  local owner mode mode_number

  if [[ -L "${CONFIG_DIR}" || ! -d "${CONFIG_DIR}" ]]; then
    return 1
  fi
  owner="$(stat -c '%u' -- "${CONFIG_DIR}" 2>/dev/null)" || return 1
  mode="$(stat -c '%a' -- "${CONFIG_DIR}" 2>/dev/null)" || return 1
  if [[ "${owner}" != "${ENV_FILE_EXPECTED_UID}" || ! "${mode}" =~ ^[0-7]{3,4}$ ]]; then
    return 1
  fi
  mode_number=$((8#${mode}))
  # A non-owner must not be able to swap the checked env path before source.
  (( (mode_number & 0022) == 0 ))
}

# Read only the approved deployment fields in a child shell. In particular, an
# installed env cannot set one-shot flags or otherwise mutate this process.
# The trusted-directory, root-owned, mode-0600 env is evaluated in an isolated
# child, whose registered values are synchronously framed into a mode-0600
# temporary file before the parent accepts them.
load_current_config() {
  local key snapshot="" owner mode

  clear_current_config
  if [[ ! -e "${ENV_FILE}" && ! -L "${ENV_FILE}" ]]; then
    if [[ ( -e "${CONFIG_DIR}" || -L "${CONFIG_DIR}" ) ]] &&
       ! validate_config_directory_security; then
      report_current_config_load_failure ""
      return 1
    fi
    return 0
  fi
  if ! validate_config_directory_security; then
    report_current_config_load_failure ""
    return 1
  fi
  if [[ -L "${ENV_FILE}" ]]; then
    report_current_config_load_failure ""
    return 1
  fi
  if [[ ! -f "${ENV_FILE}" ]]; then
    report_current_config_load_failure ""
    return 1
  fi

  if ! owner="$(stat -c '%u' -- "${ENV_FILE}" 2>/dev/null)"; then
    report_current_config_load_failure ""
    return 1
  fi
  if ! mode="$(stat -c '%a' -- "${ENV_FILE}" 2>/dev/null)"; then
    report_current_config_load_failure ""
    return 1
  fi
  if [[ ! "${ENV_FILE_EXPECTED_UID}" =~ ^[0-9]+$ || "${owner}" != "${ENV_FILE_EXPECTED_UID}" || "${mode}" != "600" ]]; then
    report_current_config_load_failure ""
    return 1
  fi

  # Do not honor TMPDIR here: this root-owned snapshot contains sourced
  # credentials, so its parent directory must not be caller-controlled.
  if ! snapshot="$(mktemp "/tmp/${SERVICE_NAME}-config.XXXXXX")"; then
    report_current_config_load_failure ""
    return 1
  fi
  if ! chmod 0600 "${snapshot}"; then
    report_current_config_load_failure "${snapshot}"
    return 1
  fi

  if ! (
    # Do not let a missing field inherit an invocation value in this child.
    unset REPO VERSION ALLOW_INSECURE_DOWNLOAD_BASE_URL SKIP_CHECKSUM INSTALLER_MODE TTY
    unset "${DEPLOYMENT_CONFIG_KEYS[@]}"
    # shellcheck disable=SC1090
    if ! . "${ENV_FILE}"; then
      exit 1
    fi
    for key in "${DEPLOYMENT_CONFIG_KEYS[@]}"; do
      builtin printf '%s\0%s\0' "${key}" "${!key-}" || exit 1
    done
  ) > "${snapshot}" 2>/dev/null; then
    report_current_config_load_failure "${snapshot}"
    return 1
  fi

  if ! read_current_config_snapshot < "${snapshot}"; then
    report_current_config_load_failure "${snapshot}"
    return 1
  fi
  if ! discard_current_config_snapshot "${snapshot}"; then
    clear_current_config
    echo "Failed to remove temporary configuration snapshot." >&2
    return 1
  fi
}

set_cfg_from_precedence() {
  local key="$1"
  local default_value="${2-}"
  local override_name="OVERRIDE_${key}"
  local override_set_name="OVERRIDE_${key}_SET"
  local current_name="CURRENT_${key}"

  if [[ "${!override_set_name}" == "true" ]]; then
    printf -v "CFG_${key}" '%s' "${!override_name}"
  elif [[ -n "${!current_name}" ]]; then
    printf -v "CFG_${key}" '%s' "${!current_name}"
  else
    printf -v "CFG_${key}" '%s' "${default_value}"
  fi
}

set_install_release_version() {
  if [[ "${OVERRIDE_VERSION_SET}" == "true" ]]; then
    printf -v CFG_RELEASE_VERSION '%s' "${OVERRIDE_VERSION}"
    return
  fi
  CFG_RELEASE_VERSION="$(resolve_release_version "" "${CURRENT_RELEASE_VERSION}")" || return
}

require_existing_installation() {
  local mode="$1"

  if [[ -f "${ENV_FILE}" ]]; then
    return 0
  fi

  case "${mode}" in
    update)
      echo "--mode=update requires an existing deployment configuration at ${ENV_FILE}." >&2
      echo "Run --mode=install for a first installation." >&2
      ;;
    reconfigure)
      echo "--mode=reconfigure requires an existing deployment configuration at ${ENV_FILE}." >&2
      echo "Run --mode=install for a first installation." >&2
      ;;
  esac
  return 1
}

adopt_current_config() {
  local key current_name

  # VERSION selects a replacement asset, but it cannot manufacture the
  # release metadata needed to identify an existing deployment safely.
  if [[ -z "${CURRENT_RELEASE_REPO}" || -z "${CURRENT_RELEASE_VERSION}" ]]; then
    echo "--mode=update requires saved RELEASE_REPO and RELEASE_VERSION metadata." >&2
    echo "Run --mode=install to re-establish saved release metadata before retrying --mode=update." >&2
    return 1
  fi

  for key in "${DEPLOYMENT_CONFIG_KEYS[@]}"; do
    current_name="CURRENT_${key}"
    printf -v "CFG_${key}" '%s' "${!current_name}"
  done
  # update intentionally ignores every deployment runtime override except the
  # explicit VERSION selector captured from the invocation environment.
  if [[ "${OVERRIDE_VERSION_SET}" == "true" ]]; then
    printf -v CFG_RELEASE_VERSION '%s' "${OVERRIDE_VERSION}"
  fi
}

prompt() {
  local label="$1"
  local default_value="${2:-}"
  local value

  if [[ -n "${default_value}" ]]; then
    read -r -p "${label} [${default_value}]: " value < "${TTY}" || return 1
    printf "%s" "${value:-${default_value}}"
  else
    read -r -p "${label}: " value < "${TTY}" || return 1
    printf "%s" "${value}"
  fi
}

prompt_required() {
  local label="$1"
  local default_value="${2:-}"
  local value

  while true; do
    if ! value="$(prompt "${label}" "${default_value}")"; then
      return 1
    fi
    if [[ -n "${value}" ]]; then
      printf "%s" "${value}"
      return
    fi
    echo "This value is required." >&2
  done
}

prompt_secret() {
  local label="$1"
  local has_existing="$2"
  local value

  if [[ "${has_existing}" == "true" ]]; then
    read -r -s -p "${label} [keep existing]: " value < "${TTY}" || return 1
    echo >&2
    printf "%s" "${value}"
  else
    while true; do
      read -r -s -p "${label}: " value < "${TTY}" || return 1
      echo >&2
      if [[ -n "${value}" ]]; then
        printf "%s" "${value}"
        return
      fi
      echo "This value is required." >&2
    done
  fi
}

prompt_optional_secret() {
  local label="$1"
  local has_existing="$2"
  local value

  if [[ "${has_existing}" == "true" ]]; then
    read -r -s -p "${label} [keep existing]: " value < "${TTY}" || return 1
  else
    read -r -s -p "${label} (optional): " value < "${TTY}" || return 1
  fi
  echo >&2
  printf "%s" "${value}"
}

collect_config_interactive() {
  local mode="$1"
  local token_input password_input
  local has_password has_token

  case "${mode}" in
    install)
      set_install_release_version
      ;;
    reconfigure)
      if [[ -z "${CURRENT_RELEASE_VERSION}" ]]; then
        echo "Existing RELEASE_VERSION is required for --mode=reconfigure." >&2
        return 1
      fi
      # Reconfiguration changes deployment settings, never the saved release.
      CFG_RELEASE_VERSION="${CURRENT_RELEASE_VERSION}"
      ;;
    *)
      echo "Invalid interactive installer mode." >&2
      return 1
      ;;
  esac

  set_cfg_from_precedence RELEASE_REPO "${DEFAULT_REPO}"
  set_cfg_from_precedence DOMAIN ""

  echo "BUPT_EC installer"
  echo
  if ! CFG_RELEASE_REPO="$(prompt_required "GitHub repository" "${CFG_RELEASE_REPO}")"; then
    return 1
  fi
  if ! CFG_DOMAIN="$(prompt_required "Domain name" "${CFG_DOMAIN}")"; then
    return 1
  fi

  set_cfg_from_precedence SSL_CERT "/etc/letsencrypt/live/${CFG_DOMAIN}/fullchain.pem"
  if ! CFG_SSL_CERT="$(prompt_required "SSL certificate path" "${CFG_SSL_CERT}")"; then
    return 1
  fi
  set_cfg_from_precedence SSL_KEY "/etc/letsencrypt/live/${CFG_DOMAIN}/privkey.pem"
  if ! CFG_SSL_KEY="$(prompt_required "SSL private key path" "${CFG_SSL_KEY}")"; then
    return 1
  fi

  set_cfg_from_precedence JW_TOKEN ""
  has_token=false
  if [[ -n "${CFG_JW_TOKEN}" ]]; then
    has_token=true
  fi
  if ! token_input="$(prompt_optional_secret "JW token override, usually leave empty" "${has_token}")"; then
    return 1
  fi
  if [[ -n "${token_input}" ]]; then
    CFG_JW_TOKEN="${token_input}"
  fi

  set_cfg_from_precedence JW_USERNAME ""
  if [[ -n "${CFG_JW_TOKEN}" ]]; then
    if ! CFG_JW_USERNAME="$(prompt "BUPT JW username, optional when JW token is set" "${CFG_JW_USERNAME}")"; then
      return 1
    fi
  elif ! CFG_JW_USERNAME="$(prompt_required "BUPT JW username" "${CFG_JW_USERNAME}")"; then
    return 1
  fi

  set_cfg_from_precedence JW_PASSWORD ""
  has_password=false
  if [[ -n "${CFG_JW_PASSWORD}" ]]; then
    has_password=true
  fi
  if [[ -n "${CFG_JW_TOKEN}" ]]; then
    if ! password_input="$(prompt_optional_secret "BUPT JW password" "${has_password}")"; then
      return 1
    fi
  elif ! password_input="$(prompt_secret "BUPT JW password" "${has_password}")"; then
    return 1
  fi
  if [[ -n "${password_input}" ]]; then
    CFG_JW_PASSWORD="${password_input}"
  fi

  set_cfg_from_precedence APP_ADDR "${DEFAULT_APP_ADDR}"
  if ! CFG_APP_ADDR="$(prompt_required "Backend listen address" "${CFG_APP_ADDR}")"; then
    return 1
  fi
  set_cfg_from_precedence DOWNLOAD_BASE_URL ""
  # These runtime settings are supported by the service but deliberately have
  # no interactive prompts.
  set_cfg_from_precedence LOG_CALLER ""
  set_cfg_from_precedence READYZ_DIAGNOSTICS ""
}

shell_quote() {
  local -a pipe_status=()

  printf "'" || return 1
  # Capture both pipeline statuses explicitly; callers often use this function
  # in an OR/! context where errexit alone would not preserve a failed writer.
  if printf "%s" "$1" | sed "s/'/'\\\\''/g"; then
    pipe_status=("${PIPESTATUS[@]}")
  else
    pipe_status=("${PIPESTATUS[@]}")
  fi
  if (( pipe_status[0] != 0 || pipe_status[1] != 0 )); then
    return 1
  fi
  printf "'" || return 1
}

validate_repo() {
  local repo="$1"
  if [[ ! "${repo}" =~ ^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$ ]]; then
    echo "Invalid GitHub repository: ${repo}" >&2
    return 1
  fi
}

resolve_release_version() {
  local explicit_version="${1:-}"
  local current_version="${2:-}"

  if [[ -n "${explicit_version}" ]]; then
    printf "%s" "${explicit_version}"
  elif [[ -n "${current_version}" ]]; then
    printf "%s" "${current_version}"
  else
    printf "latest"
  fi
}

validate_version() {
  local version="$1"
  if [[ "${version}" == "latest" || "${version}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    return
  fi
  echo "VERSION must be latest or a stable tag such as v0.1.4: ${version}" >&2
  if [[ "${version}" == "nightly" ]]; then
    echo "The nightly channel was removed in v0.3.0; rerun with VERSION=latest." >&2
    echo "That also rewrites the saved RELEASE_VERSION in ${ENV_FILE}." >&2
  fi
  return 1
}

validate_domain() {
  local domain="$1"
  if [[ ! "${domain}" =~ ^[A-Za-z0-9.-]+$ || "${domain}" == .* || "${domain}" == *. || "${domain}" == *..* ]]; then
    echo "Invalid domain name: ${domain}" >&2
    return 1
  fi
}

validate_absolute_path() {
  local label="$1"
  local path="$2"
  if [[ "${path}" != /* ]]; then
    echo "${label} must be an absolute path: ${path}" >&2
    return 1
  fi
  if [[ "${path}" == *";"* || "${path}" =~ [[:space:]] ]]; then
    echo "${label} must not contain whitespace or semicolons: ${path}" >&2
    return 1
  fi
  case "${path}" in
    *'$'* | *'#'* | *'{'* | *'}'* | *"'"* | *'"'* | *\\*)
      echo "${label} contains characters that are unsafe in the Nginx configuration." >&2
      return 1
      ;;
  esac
}

is_valid_ipv4_literal() {
  local address="$1"
  local octet
  local -a octets=()

  if [[ ! "${address}" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]; then
    return 1
  fi
  IFS=. read -r -a octets <<< "${address}"
  for octet in "${octets[@]}"; do
    if (( 10#${octet} > 255 )); then
      return 1
    fi
  done
  return 0
}

is_valid_ipv6_literal() {
  local address="$1"
  local ipv4_tail
  local left right side segment
  local compressed=false
  local count=0
  local -a segments=()

  # IPv4-mapped IPv6 remains an IPv6 literal, but count its dotted tail as
  # two hextets after independently validating the IPv4 syntax.
  if [[ "${address}" == *.* ]]; then
    ipv4_tail="${address##*:}"
    if ! is_valid_ipv4_literal "${ipv4_tail}"; then
      return 1
    fi
    address="${address%"${ipv4_tail}"}0:0"
  fi
  if [[ ! "${address}" =~ ^[0-9A-Fa-f:]+$ || "${address}" != *:* || "${address}" == *:::* ]]; then
    return 1
  fi
  if [[ "${address}" == *::* ]]; then
    compressed=true
    left="${address%%::*}"
    right="${address#*::}"
    if [[ "${right}" == *::* ]]; then
      return 1
    fi
  else
    left="${address}"
    right=""
  fi

  for side in "${left}" "${right}"; do
    if [[ -z "${side}" ]]; then
      continue
    fi
    if [[ "${side}" == :* || "${side}" == *: ]]; then
      return 1
    fi
    segments=()
    IFS=: read -r -a segments <<< "${side}"
    for segment in "${segments[@]}"; do
      if [[ ! "${segment}" =~ ^[0-9A-Fa-f]{1,4}$ ]]; then
        return 1
      fi
      count=$((count + 1))
    done
  done

  if [[ "${compressed}" == "true" ]]; then
    [[ "${count}" -lt 8 ]]
  else
    [[ "${count}" -eq 8 ]]
  fi
}

is_valid_app_hostname() {
  local host="$1"

  if [[ "${host}" == *.* && "${host}" =~ ^[0-9.]+$ ]]; then
    is_valid_ipv4_literal "${host}"
    return
  fi
  [[ "${host}" =~ ^[A-Za-z0-9]([A-Za-z0-9-]*[A-Za-z0-9])?(\.[A-Za-z0-9]([A-Za-z0-9-]*[A-Za-z0-9])?)*$ ]]
}

validate_app_addr() {
  local app_addr="$1"
  local host port

  if [[ "${app_addr}" =~ ^\[([0-9A-Fa-f:.]+)\]:([0-9]{1,5})$ ]]; then
    host="${BASH_REMATCH[1]}"
    port="${BASH_REMATCH[2]}"
    if ! is_valid_ipv6_literal "${host}"; then
      echo "Invalid backend listen address." >&2
      return 1
    fi
  elif [[ "${app_addr}" =~ ^([^:]+):([0-9]{1,5})$ ]]; then
    host="${BASH_REMATCH[1]}"
    port="${BASH_REMATCH[2]}"
    if ! is_valid_app_hostname "${host}"; then
      echo "Invalid backend listen address." >&2
      return 1
    fi
  else
    echo "Invalid backend listen address." >&2
    return 1
  fi

  if (( 10#${port} < 1 || 10#${port} > 65535 )); then
    echo "Backend listen port is out of range." >&2
    return 1
  fi
}

current_config_load_guidance() {
  echo "Repair the installed configuration ownership, mode, or syntax before retrying." >&2
  echo "If it cannot be repaired, move it aside and run --mode=install to rebuild it." >&2
}

version_recovery_guidance() {
  case "${INSTALLER_MODE}" in
    update)
      echo "Retry --mode=update with a valid VERSION, or omit VERSION to reuse valid saved release metadata." >&2
      ;;
    reconfigure)
      echo "Run --mode=install with a valid VERSION to repair saved release metadata." >&2
      ;;
  esac
}

config_recovery_guidance() {
  if [[ "${INSTALLER_MODE}" == "update" ]]; then
    echo "Fix the saved deployment configuration with --mode=reconfigure before retrying --mode=update." >&2
  fi
}

validate_config() {
  if [[ ( -e "${CONFIG_DIR}" || -L "${CONFIG_DIR}" ) ]] &&
     ! validate_config_directory_security; then
    echo "The installation configuration directory has unsafe ownership, mode, or symlink layout." >&2
    current_config_load_guidance
    return 1
  fi
  if [[ -z "${CFG_RELEASE_REPO}" ]]; then
    echo "RELEASE_REPO is required." >&2
    config_recovery_guidance
    return 1
  fi
  if ! validate_repo "${CFG_RELEASE_REPO}"; then
    config_recovery_guidance
    return 1
  fi
  if [[ -z "${CFG_RELEASE_VERSION}" ]]; then
    echo "RELEASE_VERSION is required." >&2
    version_recovery_guidance
    return 1
  fi
  if ! validate_version "${CFG_RELEASE_VERSION}"; then
    version_recovery_guidance
    return 1
  fi
  if [[ "${OVERRIDE_VERSION_SET}" == "true" &&
        "${CFG_RELEASE_VERSION}" != "${CURRENT_RELEASE_VERSION}" &&
        -n "${CURRENT_DOWNLOAD_BASE_URL}" ]]; then
    if [[ "${INSTALLER_MODE}" == "update" ]]; then
      echo "A saved custom DOWNLOAD_BASE_URL cannot prove it serves the explicitly selected VERSION." >&2
      echo "Run --mode=install with that VERSION and a matching trusted DOWNLOAD_BASE_URL." >&2
      return 1
    fi
    if [[ "${INSTALLER_MODE}" == "install" && "${OVERRIDE_DOWNLOAD_BASE_URL_SET}" != "true" ]]; then
      echo "Changing VERSION with a saved custom mirror requires an explicit matching DOWNLOAD_BASE_URL." >&2
      return 1
    fi
  fi
  if [[ -z "${CFG_DOMAIN}" ]]; then
    echo "DOMAIN is required." >&2
    config_recovery_guidance
    return 1
  fi
  if ! validate_domain "${CFG_DOMAIN}"; then
    config_recovery_guidance
    return 1
  fi
  if [[ -z "${CFG_SSL_CERT}" ]]; then
    echo "SSL certificate path is required." >&2
    config_recovery_guidance
    return 1
  fi
  if ! validate_absolute_path "SSL certificate path" "${CFG_SSL_CERT}"; then
    config_recovery_guidance
    return 1
  fi
  if [[ -z "${CFG_SSL_KEY}" ]]; then
    echo "SSL private key path is required." >&2
    config_recovery_guidance
    return 1
  fi
  if ! validate_absolute_path "SSL private key path" "${CFG_SSL_KEY}"; then
    config_recovery_guidance
    return 1
  fi
  if [[ -z "${CFG_APP_ADDR}" ]]; then
    echo "Backend listen address is required." >&2
    config_recovery_guidance
    return 1
  fi
  if ! validate_app_addr "${CFG_APP_ADDR}"; then
    config_recovery_guidance
    return 1
  fi
  if [[ -z "${CFG_JW_TOKEN}" && ( -z "${CFG_JW_USERNAME}" || -z "${CFG_JW_PASSWORD}" ) ]]; then
    echo "JW_TOKEN or both JW_USERNAME and JW_PASSWORD are required." >&2
    config_recovery_guidance
    return 1
  fi

  VALIDATED_DOWNLOAD_BASE_URL=""
  if ! validate_download_base_url "${CFG_DOWNLOAD_BASE_URL}"; then
    config_recovery_guidance
    return 1
  fi
  # Persist and download only the normalized form (no userinfo/query/fragment).
  CFG_DOWNLOAD_BASE_URL="${VALIDATED_DOWNLOAD_BASE_URL}"

  if [[ ! -f "${CFG_SSL_CERT}" ]]; then
    echo "SSL certificate not found: ${CFG_SSL_CERT}" >&2
    config_recovery_guidance
    return 1
  fi
  if [[ ! -f "${CFG_SSL_KEY}" ]]; then
    echo "SSL private key not found: ${CFG_SSL_KEY}" >&2
    config_recovery_guidance
    return 1
  fi
}

reset_config_state

# shellcheck shell=bash
# shellcheck disable=SC2034

# normalize_download_base_url validates and normalizes DOWNLOAD_BASE_URL.
# Empty input prints an empty string (official GitHub path). Invalid input exits
# non-zero with a rule-only error that never echoes the raw URL (no secrets).
# On success prints scheme://host[:port][/path] with trailing slashes stripped.
normalize_download_base_url() {
  local url="$1"
  local scheme rest authority path host port host_display normalized

  if [[ -z "${url}" ]]; then
    printf ""
    return 0
  fi

  if [[ "${url}" == *";"* || "${url}" =~ [[:space:]] ]]; then
    echo "DOWNLOAD_BASE_URL must not contain whitespace or semicolons." >&2
    return 1
  fi
  if [[ "${url}" == *"?"* ]]; then
    echo "DOWNLOAD_BASE_URL must not contain a query string." >&2
    return 1
  fi
  if [[ "${url}" == *"#"* ]]; then
    echo "DOWNLOAD_BASE_URL must not contain a URL fragment." >&2
    return 1
  fi
  if [[ "${url}" == *"@"* ]]; then
    echo "DOWNLOAD_BASE_URL must not contain userinfo credentials." >&2
    return 1
  fi

  if [[ ! "${url}" =~ ^([A-Za-z][A-Za-z0-9+.-]*)://(.*)$ ]]; then
    echo "DOWNLOAD_BASE_URL must be an absolute http(s) URL." >&2
    return 1
  fi
  scheme="$(printf '%s' "${BASH_REMATCH[1]}" | tr '[:upper:]' '[:lower:]')"
  rest="${BASH_REMATCH[2]}"

  case "${scheme}" in
    https) ;;
    http)
      if [[ "${ALLOW_INSECURE_DOWNLOAD_BASE_URL:-false}" != "true" ]]; then
        echo "DOWNLOAD_BASE_URL must use https://. Set ALLOW_INSECURE_DOWNLOAD_BASE_URL=true only for a trusted local mirror." >&2
        return 1
      fi
      ;;
    *)
      # Insecure opt-in only widens HTTPS→HTTP; never file/ftp/data/etc.
      echo "DOWNLOAD_BASE_URL scheme must be https (or http only with ALLOW_INSECURE_DOWNLOAD_BASE_URL=true)." >&2
      return 1
      ;;
  esac

  if [[ -z "${rest}" ]]; then
    echo "DOWNLOAD_BASE_URL must include a non-empty host." >&2
    return 1
  fi

  if [[ "${rest}" == *"/"* ]]; then
    authority="${rest%%/*}"
    path="/${rest#*/}"
  else
    authority="${rest}"
    path=""
  fi

  if [[ -z "${authority}" ]]; then
    echo "DOWNLOAD_BASE_URL must include a non-empty host." >&2
    return 1
  fi

  host=""
  port=""
  host_display=""
  if [[ "${authority}" == \[* ]]; then
    if [[ ! "${authority}" =~ ^\[([0-9A-Fa-f:]+)\](:([0-9]{1,5}))?$ ]]; then
      echo "DOWNLOAD_BASE_URL IPv6 host must be bracketed and may include a valid port." >&2
      return 1
    fi
    host="${BASH_REMATCH[1]}"
    port="${BASH_REMATCH[3]:-}"
    if [[ -z "${host}" ]]; then
      echo "DOWNLOAD_BASE_URL must include a non-empty host." >&2
      return 1
    fi
    host_display="[${host}]"
  else
    if [[ "${authority}" == *:* ]]; then
      host="${authority%:*}"
      port="${authority##*:}"
      if [[ -z "${host}" || "${host}" == *:* ]]; then
        echo "DOWNLOAD_BASE_URL host is invalid; use brackets for IPv6 addresses." >&2
        return 1
      fi
    else
      host="${authority}"
      port=""
    fi
    if [[ -z "${host}" ]]; then
      echo "DOWNLOAD_BASE_URL must include a non-empty host." >&2
      return 1
    fi
    # Hostname / IPv4: labels, dots, hyphens only (no credentials or odd markup).
    if [[ ! "${host}" =~ ^[A-Za-z0-9]([A-Za-z0-9.-]*[A-Za-z0-9])?$ && ! "${host}" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]; then
      echo "DOWNLOAD_BASE_URL host is invalid." >&2
      return 1
    fi
    host_display="${host}"
  fi

  if [[ -n "${port}" ]]; then
    if [[ ! "${port}" =~ ^[0-9]+$ ]] || ((10#${port} < 1 || 10#${port} > 65535)); then
      echo "DOWNLOAD_BASE_URL port is out of range." >&2
      return 1
    fi
  fi

  if [[ -n "${path}" ]]; then
    # Strip trailing slashes; empty path after strip means authority only.
    while [[ "${path}" == */ ]]; do
      path="${path%/}"
    done
    if [[ -n "${path}" && ! "${path}" =~ ^/[A-Za-z0-9._~/-]+$ ]]; then
      echo "DOWNLOAD_BASE_URL path contains unsupported characters." >&2
      return 1
    fi
  fi

  normalized="${scheme}://${host_display}"
  if [[ -n "${port}" ]]; then
    normalized+=":${port}"
  fi
  if [[ -n "${path}" ]]; then
    normalized+="${path}"
  fi

  printf "%s" "${normalized}"
  return 0
}

# Scheme of a normalized download base (http or https). Empty → https default.
download_base_scheme() {
  local url="${1:-}"
  case "${url}" in
    http://*)
      printf 'http'
      ;;
    *)
      printf 'https'
      ;;
  esac
}

# Safe host label from a normalized base: hostname, IPv4, or bracketed IPv6.
download_base_safe_host() {
  local url="${1:-}"
  local rest authority
  if [[ -z "${url}" ]]; then
    printf ''
    return 0
  fi
  rest="${url#*://}"
  authority="${rest%%/*}"
  if [[ "${authority}" == \[* ]]; then
    if [[ "${authority}" =~ ^(\[[0-9A-Fa-f:]+\]) ]]; then
      printf '%s' "${BASH_REMATCH[1]}"
      return 0
    fi
    printf ''
    return 0
  fi
  printf '%s' "${authority%%:*}"
}

validate_download_base_url() {
  local url="$1"
  local normalized

  VALIDATED_DOWNLOAD_BASE_URL=""
  if ! normalized="$(normalize_download_base_url "${url}")"; then
    return 1
  fi
  if [[ -z "${normalized}" ]]; then
    return 0
  fi
  if [[ "$(download_base_scheme "${normalized}")" == "http" ]]; then
    echo "Warning: using non-HTTPS DOWNLOAD_BASE_URL because ALLOW_INSECURE_DOWNLOAD_BASE_URL=true." >&2
  fi
  # Expose normalized base for main to persist and download without re-parsing.
  VALIDATED_DOWNLOAD_BASE_URL="${normalized}"
}

# curl_download_proto_args prints --proto / --proto-redir tokens for the
# validated scheme (or defaults to HTTPS-only for official GitHub downloads).
curl_download_proto_args() {
  local scheme="${1:-https}"
  if [[ "${scheme}" == "http" ]]; then
    printf '%s\0' --proto '=http,https' --proto-redir '=http,https'
  else
    printf '%s\0' --proto '=https' --proto-redir '=https'
  fi
}

safe_download_base_label() {
  local base_url="${1:-}"
  local scheme host
  scheme="$(download_base_scheme "${base_url}")"
  host="$(download_base_safe_host "${base_url}")"
  if [[ -n "${host}" ]]; then
    printf 'operator-configured %s mirror host %s' "$(printf '%s' "${scheme}" | tr '[:lower:]' '[:upper:]')" "${host}"
  else
    printf 'configured mirror'
  fi
}

detect_arch() {
  local machine
  machine="$(uname -m)"
  case "${machine}" in
    x86_64 | amd64)
      printf "amd64"
      ;;
    aarch64 | arm64)
      printf "arm64"
      ;;
    *)
      echo "Unsupported CPU architecture: ${machine}" >&2
      exit 1
      ;;
  esac
}

install_packages() {
  if command -v apt-get >/dev/null 2>&1; then
    export DEBIAN_FRONTEND=noninteractive
    apt-get update || return
    apt-get install -y ca-certificates curl tar nginx || return
  else
    echo "This installer currently supports apt-based systems such as Debian 12." >&2
    return 1
  fi
}

create_user() {
  if ! getent group "${APP_GROUP}" >/dev/null 2>&1; then
    groupadd --system "${APP_GROUP}" || return
  fi

  if ! id "${APP_USER}" >/dev/null 2>&1; then
    useradd --system --home "${INSTALL_DIR}" --shell /usr/sbin/nologin --gid "${APP_GROUP}" "${APP_USER}" || return
  fi
}

host_reachable() {
  local host="$1"
  curl -fsSIL --connect-timeout 5 --max-time 10 "https://${host}/" >/dev/null 2>&1
}

# Official GitHub releases are the only automatic trust boundary. Operators may
# point DOWNLOAD_BASE_URL at an explicit mirror they already trust; same-origin
# checksums then prove download integrity only, not independent publisher identity.
# override_url must already be normalized (validate_download_base_url) when set.
resolve_download_base_url() {
  local repo="$1"
  local version="$2"
  local override_url="$3"
  local normalized label

  if [[ -n "${override_url}" ]]; then
    # Always re-validate so callers cannot bypass shape checks; never log raw input.
    if ! normalized="$(normalize_download_base_url "${override_url}")"; then
      exit 1
    fi
    label="$(safe_download_base_label "${normalized}")"
    echo "Using ${label}." >&2
    echo "Warning: package and checksums.txt come from this operator-trusted source. Same-origin checksums verify integrity, not independent GitHub publisher identity." >&2
    printf "%s" "${normalized}"
    return
  fi

  if ! host_reachable "${GITHUB_HOST}"; then
    echo "GitHub (${GITHUB_HOST}) is not reachable." >&2
    echo "The installer no longer auto-selects third-party proxies." >&2
    echo "Mirror the release assets to an HTTPS location you control, then rerun with:" >&2
    echo "  DOWNLOAD_BASE_URL=https://your-mirror.example/path VERSION=<latest|vX.Y.Z>" >&2
    echo "Package and checksums.txt must both be present under that base URL." >&2
    exit 1
  fi

  if [[ "${version}" == "latest" ]]; then
    printf "https://%s/%s/releases/latest/download" "${GITHUB_HOST}" "${repo}"
  else
    printf "https://%s/%s/releases/download/%s" "${GITHUB_HOST}" "${repo}" "${version}"
  fi
}

download_release() {
  local repo="$1"
  local version="$2"
  local arch="$3"
  local work_dir="$4"
  local download_base_url="$5"
  local package_name="bupt-ec-linux-${arch}.tar.gz"
  local base_url
  local -a proto_args=()
  local scheme="https"
  local arg

  if ! base_url="$(resolve_download_base_url "${repo}" "${version}" "${download_base_url}")"; then
    return 1
  fi
  scheme="$(download_base_scheme "${base_url}")"
  while IFS= read -r -d '' arg; do
    proto_args+=("${arg}")
  done < <(curl_download_proto_args "${scheme}")

  if [[ -n "${download_base_url}" ]]; then
    echo "Downloading ${repo} ${version} (${arch}) from configured mirror..."
  else
    echo "Downloading ${repo} ${version} (${arch}) from official GitHub releases..."
  fi
  curl -fL "${proto_args[@]}" "${base_url}/${package_name}" -o "${work_dir}/${package_name}" || return

  # Checksum verification is required by default (fail-closed).
  # Break-glass only: SKIP_CHECKSUM=1 skips verification with a loud warning.
  if [[ "${SKIP_CHECKSUM:-}" == "1" ]]; then
    echo "WARNING: SKIP_CHECKSUM=1 is set; skipping package checksum verification. This is insecure." >&2
    return
  fi

  if ! curl -fsL "${proto_args[@]}" "${base_url}/checksums.txt" -o "${work_dir}/checksums.txt"; then
    echo "Failed to download checksums.txt from configured source; refusing to install without verification." >&2
    echo "Set SKIP_CHECKSUM=1 only as an explicit break-glass to skip verification." >&2
    exit 1
  fi

  if ! grep -q " ${package_name}$" "${work_dir}/checksums.txt"; then
    echo "checksums.txt has no entry for ${package_name}; refusing to install." >&2
    exit 1
  fi

  echo "Verifying package checksum..."
  (cd "${work_dir}" && grep " ${package_name}$" checksums.txt | sha256sum -c -)
}

stage_release() {
  local archive="$1"
  local work_dir="$2"
  local staging_dir="$3"
  local extract_dir="${work_dir}/extract"
  local binary_path

  rm -rf "${extract_dir}" "${staging_dir}" || return
  mkdir -p "${extract_dir}" "${staging_dir}" || return
  chmod 0700 "${extract_dir}" "${staging_dir}" || return
  if ! tar -xzf "${archive}" -C "${extract_dir}"; then
    echo "Failed to extract release archive." >&2
    return 1
  fi

  if ! binary_path="$(find "${extract_dir}" -type f -name bupt-ec -print -quit)"; then
    echo "Failed to inspect extracted release archive." >&2
    return 1
  fi
  if [[ -z "${binary_path}" ]]; then
    echo "Release archive does not contain bupt-ec binary." >&2
    return 1
  fi
  install -m 0755 "${binary_path}" "${staging_dir}/bupt-ec" || return
  chown root:root "${staging_dir}/bupt-ec" || return
}

# shellcheck shell=bash

render_env_file() {
  local destination="$1"
  local key value_name

  (
    umask 077 || exit 1
    {
      for key in "${DEPLOYMENT_CONFIG_KEYS[@]}"; do
        value_name="CFG_${key}"
        printf '%s=' "${key}" || exit 1
        shell_quote "${!value_name-}" || exit 1
        printf '\n' || exit 1
      done
    } > "${destination}" || exit 1
  ) || return 1
  chmod 0600 "${destination}" || return 1
  chown root:root "${destination}" || return 1
}

render_systemd_service() {
  local destination="$1"

  cat > "${destination}" <<EOF || return
[Unit]
Description=BUPT_EC
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=${APP_USER}
Group=${APP_GROUP}
WorkingDirectory=${INSTALL_DIR}
EnvironmentFile=${ENV_FILE}
ExecStart=${INSTALL_DIR}/bupt-ec
Restart=always
RestartSec=5
UMask=0077
NoNewPrivileges=true
PrivateTmp=true
PrivateDevices=true
ProtectHome=true
ProtectSystem=full
ProtectClock=true
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectKernelLogs=true
ProtectControlGroups=true
LockPersonality=true
RestrictSUIDSGID=true
CapabilityBoundingSet=
RestrictAddressFamilies=AF_INET AF_INET6 AF_UNIX
SystemCallArchitectures=native
ReadWritePaths=${INSTALL_DIR}/run_log

[Install]
WantedBy=multi-user.target
EOF
  chmod 0644 "${destination}" || return
  chown root:root "${destination}" || return
}

render_nginx_site() {
  local destination="$1"

  cat > "${destination}" <<EOF || return
limit_req_zone \$binary_remote_addr zone=bupt_ec_api:10m rate=30r/m;

server {
    listen 80;
    listen [::]:80;
    server_name ${CFG_DOMAIN};
    return 301 https://\$host\$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name ${CFG_DOMAIN};

    ssl_certificate ${CFG_SSL_CERT};
    ssl_certificate_key ${CFG_SSL_KEY};
    ssl_protocols TLSv1.2 TLSv1.3;

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "same-origin" always;
    add_header X-Frame-Options "DENY" always;
    add_header Content-Security-Policy "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; frame-ancestors 'none'" always;

    # Runtime metrics are loopback-only; do not proxy them to the public site.
    location = /metrics {
        return 404;
    }

    location /api/ {
        limit_req zone=bupt_ec_api burst=20 nodelay;
        proxy_pass http://${CFG_APP_ADDR};
        proxy_http_version 1.1;
        proxy_connect_timeout 5s;
        proxy_send_timeout 15s;
        # Exceeds ClassroomRefreshLimit (30s) and Go WriteTimeout (15s) so a cold
        # refresh near the backend budget can still return JSON through the proxy.
        proxy_read_timeout 60s;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    location / {
        proxy_pass http://${CFG_APP_ADDR};
        proxy_http_version 1.1;
        proxy_connect_timeout 5s;
        proxy_send_timeout 15s;
        proxy_read_timeout 30s;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
EOF
  chmod 0644 "${destination}" || return
  chown root:root "${destination}" || return
}

prepare_staging() {
  local archive="$1"
  local work_dir="$2"
  local staging_dir="$3"

  stage_release "${archive}" "${work_dir}" "${staging_dir}" || return
  render_env_file "${staging_dir}/bupt-ec.env" || return
  render_systemd_service "${staging_dir}/${SERVICE_NAME}.service" || return
  render_nginx_site "${staging_dir}/${SERVICE_NAME}.conf" || return
}

# shellcheck shell=bash
# shellcheck disable=SC2153

transaction_targets() {
  printf '%s\t%s\n' \
    binary "${INSTALL_DIR}/bupt-ec" \
    env "${ENV_FILE}" \
    service "${SERVICE_FILE}" \
    systemd_enabled "${SYSTEMD_ENABLED_LINK}" \
    nginx_site "${NGINX_SITE}" \
    nginx_enabled "${NGINX_ENABLED}"
}

write_runtime_snapshot() {
  local destination="$1"
  local service_present=0
  local service_enabled=0
  local service_active=0
  local nginx_site_present=0
  local nginx_enabled=0

  if [[ -e "${SERVICE_FILE}" || -L "${SERVICE_FILE}" ]]; then
    service_present=1
  fi
  if systemctl is-enabled --quiet "${SERVICE_NAME}" 2>/dev/null; then
    service_enabled=1
  fi
  if systemctl is-active --quiet "${SERVICE_NAME}" 2>/dev/null; then
    service_active=1
  fi
  if [[ -e "${NGINX_SITE}" || -L "${NGINX_SITE}" ]]; then
    nginx_site_present=1
  fi
  if [[ -e "${NGINX_ENABLED}" || -L "${NGINX_ENABLED}" ]]; then
    nginx_enabled=1
  fi

  (umask 077; cat > "${destination}" <<EOF
service_present=${service_present}
service_enabled=${service_enabled}
service_active=${service_active}
nginx_site_present=${nginx_site_present}
nginx_enabled=${nginx_enabled}
EOF
  ) || return
  chmod 0600 "${destination}" || return
}

read_runtime_snapshot_value() {
  local snapshot="$1"
  local key="$2"
  local line value

  line="$(grep -E "^${key}=" "${snapshot}" 2>/dev/null || true)"
  value="${line#*=}"
  if [[ "${value}" == "1" ]]; then
    printf '1'
  else
    printf '0'
  fi
}

snapshot_installation() {
  local backup_dir="$1"
  local manifest="${backup_dir}/manifest"
  local runtime_state="${backup_dir}/runtime_state"
  local role target

  rm -rf "${backup_dir}" || return
  mkdir -p "${backup_dir}" || return
  chmod 0700 "${backup_dir}" || return
  (umask 077; : > "${manifest}") || return

  while IFS=$'\t' read -r role target; do
    if [[ -e "${target}" || -L "${target}" ]]; then
      if ! cp -a -- "${target}" "${backup_dir}/${role}"; then
        echo "Failed to snapshot ${role}." >&2
        return 1
      fi
      printf '%s\t1\t%s\n' "${role}" "${target}" >> "${manifest}" || return
    else
      printf '%s\t0\t%s\n' "${role}" "${target}" >> "${manifest}" || return
    fi
  done < <(transaction_targets)
  chmod 0600 "${manifest}" || return
  if [[ -f "${backup_dir}/env" ]]; then
    chmod 0600 "${backup_dir}/env" || return
  fi
  write_runtime_snapshot "${runtime_state}" || return
}

atomic_install_file() {
  local source="$1"
  local target="$2"
  local mode="$3"
  local owner="$4"
  local target_dir tmp

  target_dir="$(dirname "${target}")"
  tmp="${target}.new.$$"
  mkdir -p "${target_dir}" || return
  rm -f -- "${tmp}" || return
  install -m "${mode}" "${source}" "${tmp}" || { rm -f -- "${tmp}"; return 1; }
  chown "${owner}" "${tmp}" || { rm -f -- "${tmp}"; return 1; }
  mv -Tf -- "${tmp}" "${target}" || { rm -f -- "${tmp}"; return 1; }
}

atomic_install_symlink() {
  local link_target="$1"
  local target="$2"
  local target_dir tmp

  target_dir="$(dirname "${target}")"
  tmp="${target}.new.$$"
  mkdir -p "${target_dir}" || return
  rm -f -- "${tmp}" || return
  ln -s "${link_target}" "${tmp}" || { rm -f -- "${tmp}"; return 1; }
  mv -Tf -- "${tmp}" "${target}" || { rm -f -- "${tmp}"; return 1; }
}

restore_snapshot_target() {
  local backup="$1"
  local target="$2"
  local target_dir tmp

  target_dir="$(dirname "${target}")"
  tmp="${target}.rollback.$$"
  mkdir -p "${target_dir}" || return
  rm -rf -- "${tmp}" || return
  cp -a -- "${backup}" "${tmp}" || { rm -rf -- "${tmp}"; return 1; }
  mv -Tf -- "${tmp}" "${target}" || { rm -rf -- "${tmp}"; return 1; }
}

rollback_installation() {
  local backup_dir="$1"
  local role existed target
  local failed=0
  local runtime_state="${backup_dir}/runtime_state"
  local service_present=0
  local service_enabled=0
  local service_active=0

  if [[ ! -r "${backup_dir}/manifest" ]]; then
    echo "Rollback manifest is missing or unreadable." >&2
    return 1
  fi

  if [[ -r "${runtime_state}" ]]; then
    service_present="$(read_runtime_snapshot_value "${runtime_state}" service_present)"
    service_enabled="$(read_runtime_snapshot_value "${runtime_state}" service_enabled)"
    service_active="$(read_runtime_snapshot_value "${runtime_state}" service_active)"
  fi

  echo "Installation failed; rolling back previous files..." >&2

  # Stop any running unit before replacing/removing files so first-install late
  # failures cannot leave a process without a unit file.
  if systemctl is-active --quiet "${SERVICE_NAME}" 2>/dev/null; then
    if ! systemctl stop "${SERVICE_NAME}" >/dev/null 2>&1; then
      echo "Rollback failed while stopping ${SERVICE_NAME}." >&2
      failed=1
    fi
  fi

  while IFS=$'\t' read -r role existed target; do
    if ! rm -f -- "${target}.new.$$" "${target}.rollback.$$"; then
      echo "Rollback failed while cleaning temporary ${role} files." >&2
      failed=1
    fi
    if [[ "${existed}" == "1" ]]; then
      if ! restore_snapshot_target "${backup_dir}/${role}" "${target}"; then
        echo "Rollback failed while restoring ${role}." >&2
        failed=1
      fi
    elif ! rm -rf -- "${target}"; then
      echo "Rollback failed while removing new ${role}." >&2
      failed=1
    fi
  done < "${backup_dir}/manifest"

  if ! systemctl daemon-reload >/dev/null 2>&1; then
    echo "Rollback failed during systemctl daemon-reload." >&2
    failed=1
  fi

  if [[ "${service_present}" == "1" ]]; then
    if [[ "${service_enabled}" == "1" ]]; then
      if ! systemctl enable "${SERVICE_NAME}" >/dev/null 2>&1; then
        echo "Rollback failed while re-enabling ${SERVICE_NAME}." >&2
        failed=1
      fi
    else
      if ! systemctl disable "${SERVICE_NAME}" >/dev/null 2>&1; then
        echo "Rollback failed while disabling ${SERVICE_NAME}." >&2
        failed=1
      fi
    fi
    if [[ "${service_active}" == "1" ]]; then
      if ! systemctl start "${SERVICE_NAME}" >/dev/null 2>&1; then
        echo "Rollback failed while starting previous ${SERVICE_NAME}." >&2
        failed=1
      fi
    fi
  else
    # First install: ensure enablement is gone and the unit is not left active.
    rm -f -- "${SYSTEMD_ENABLED_LINK}" >/dev/null 2>&1 || failed=1
    if systemctl is-active --quiet "${SERVICE_NAME}" 2>/dev/null; then
      if ! systemctl stop "${SERVICE_NAME}" >/dev/null 2>&1; then
        echo "Rollback failed while stopping new ${SERVICE_NAME}." >&2
        failed=1
      fi
    fi
  fi

  # Always revalidate and reload Nginx so a newly loaded site is dropped even
  # when no previous site existed (first-install late failure after reload).
  if ! nginx -t >/dev/null 2>&1; then
    echo "Rollback failed during nginx configuration test." >&2
    failed=1
  fi
  if ! systemctl reload nginx >/dev/null 2>&1; then
    echo "Rollback failed while reloading nginx." >&2
    failed=1
  fi

  if (( failed == 0 )); then
    echo "Rollback completed." >&2
  else
    echo "Rollback completed with errors; inspect systemd and nginx state." >&2
  fi
  return "${failed}"
}

local_health_url() {
  local app_addr="$1"
  if [[ "${app_addr}" =~ ^(127\.0\.0\.1|localhost):[0-9]{1,5}$ || "${app_addr}" =~ ^\[::1\]:[0-9]{1,5}$ ]]; then
    printf 'http://%s/healthz' "${app_addr}"
    return
  fi
  return 1
}

wait_for_health() {
  local health_url="$1"
  local attempt

  for attempt in {1..10}; do
    if curl -fsS --noproxy '*' --connect-timeout 2 --max-time 2 "${health_url}" >/dev/null; then
      return
    fi
    if (( attempt < 10 )); then
      sleep 1
    fi
  done

  echo "Service health check failed: ${health_url}" >&2
  return 1
}

commit_installation() {
  local staging_dir="$1"
  local app_addr="$2"
  local health_url

  mkdir -p "${INSTALL_DIR}/run_log" "${CONFIG_DIR}" || return
  chmod 0755 "${INSTALL_DIR}" || return
  chown root:root "${INSTALL_DIR}" || return
  chown -R "${APP_USER}:${APP_GROUP}" "${INSTALL_DIR}/run_log" || return
  chmod 0750 "${INSTALL_DIR}/run_log" || return

  atomic_install_file "${staging_dir}/bupt-ec" "${INSTALL_DIR}/bupt-ec" 0755 root:root || return
  atomic_install_file "${staging_dir}/bupt-ec.env" "${ENV_FILE}" 0600 root:root || return
  atomic_install_file "${staging_dir}/${SERVICE_NAME}.service" "${SERVICE_FILE}" 0644 root:root || return
  atomic_install_file "${staging_dir}/${SERVICE_NAME}.conf" "${NGINX_SITE}" 0644 root:root || return
  atomic_install_symlink "${NGINX_SITE}" "${NGINX_ENABLED}" || return

  systemctl daemon-reload || return
  systemctl enable "${SERVICE_NAME}" || return
  nginx -t || return
  systemctl restart "${SERVICE_NAME}" || return
  systemctl is-active --quiet "${SERVICE_NAME}" || return
  systemctl reload nginx || return

  if health_url="$(local_health_url "${app_addr}")"; then
    wait_for_health "${health_url}" || return
  else
    echo "Skipping local health check for non-loopback APP_ADDR=${app_addr}." >&2
  fi
}

perform_install_transaction() {
  local staging_dir="$1"
  local backup_dir="$2"
  local app_addr="$3"
  local status

  snapshot_installation "${backup_dir}" || return
  TRANSACTION_BACKUP_DIR="${backup_dir}"
  TRANSACTION_ACTIVE=true
  commit_installation "${staging_dir}" "${app_addr}" || {
    status=$?
    return "${status}"
  }
  TRANSACTION_ACTIVE=false
  if ! rm -rf "${backup_dir}"; then
    echo "Installation validated, but the transaction backup could not be removed." >&2
    return 1
  fi
  TRANSACTION_BACKUP_DIR=""
}

installer_cleanup() {
  local status="$1"
  local rollback_status=0
  local preserve_tmp=false

  trap - ERR EXIT
  set +e
  if [[ "${TRANSACTION_ACTIVE}" == "true" && -n "${TRANSACTION_BACKUP_DIR}" ]]; then
    if (( status == 0 )); then
      status=1
    fi
    rollback_installation "${TRANSACTION_BACKUP_DIR}"
    rollback_status=$?
    if (( rollback_status != 0 )); then
      preserve_tmp=true
    fi
  fi
  if [[ -n "${INSTALLER_TMP_DIR}" && "${preserve_tmp}" == "false" ]]; then
    rm -rf "${INSTALLER_TMP_DIR}"
  fi
  if (( rollback_status != 0 )); then
    echo "Automatic rollback was incomplete; root-only recovery files were preserved at ${TRANSACTION_BACKUP_DIR}." >&2
  fi
  exit "${status}"
}

initialize_installer_session() {
  local tmp_dir="$1"
  INSTALLER_TMP_DIR="${tmp_dir}"
  trap 'installer_cleanup "$?"' EXIT
}

# shellcheck shell=bash

require_update_tools() {
  local tool
  local -a required_tools=(curl tar sha256sum install systemctl nginx)

  for tool in "${required_tools[@]}"; do
    if ! command -v "${tool}" >/dev/null 2>&1; then
      echo "--mode=update requires ${tool}; install the required system tools or rerun with --mode=install on a supported apt-based system." >&2
      return 1
    fi
  done
}

execute_deployment() {
  local arch tmp_dir archive staging_dir backup_dir previous_umask transaction_status

  # update never runs apt. Check every non-core deployment command before
  # creating a session, downloading assets, or taking a transaction snapshot.
  if [[ "${INSTALLER_MODE}" == "update" ]]; then
    require_update_tools || return
  fi

  arch="$(detect_arch)" || return
  tmp_dir="$(mktemp -d)" || return
  if ! chmod 0700 "${tmp_dir}"; then
    rm -rf -- "${tmp_dir}" || true
    return 1
  fi
  initialize_installer_session "${tmp_dir}"
  staging_dir="${tmp_dir}/staging"
  backup_dir="${tmp_dir}/backup"

  if [[ "${INSTALLER_MODE}" != "update" ]]; then
    install_packages || return
  fi
  create_user || return
  download_release "${CFG_RELEASE_REPO}" "${CFG_RELEASE_VERSION}" "${arch}" "${tmp_dir}" "${CFG_DOWNLOAD_BASE_URL}" || return
  archive="${tmp_dir}/bupt-ec-linux-${arch}.tar.gz"
  prepare_staging "${archive}" "${tmp_dir}" "${staging_dir}" || return

  # commit_installation creates fixed installation/config directories. Force a
  # safe creation mode even when root invoked the installer with a permissive
  # umask, then restore the caller's value on every transaction result.
  previous_umask="$(umask)" || return
  umask 022 || return
  transaction_status=0
  perform_install_transaction "${staging_dir}" "${backup_dir}" "${CFG_APP_ADDR}" || transaction_status=$?
  if ! umask "${previous_umask}"; then
    return 1
  fi
  return "${transaction_status}"
}

print_completion_summary() {
  case "${INSTALLER_MODE}" in
    install)
      # Keep the compatible default-install completion text byte-for-byte.
      echo
      echo "BUPT_EC is installed."
      echo "URL: https://${CFG_DOMAIN}/"
      echo "Service: systemctl status ${SERVICE_NAME}"
      echo "Upgrade later: rerun this installer."
      ;;
    update)
      echo
      echo "BUPT_EC update completed."
      echo "Version: ${CFG_RELEASE_VERSION}"
      echo "URL: https://${CFG_DOMAIN}/"
      echo "Service: systemctl status ${SERVICE_NAME}"
      ;;
    reconfigure)
      echo
      echo "BUPT_EC reconfiguration completed."
      echo "Version: ${CFG_RELEASE_VERSION}"
      echo "URL: https://${CFG_DOMAIN}/"
      echo "Service: systemctl status ${SERVICE_NAME}"
      ;;
  esac
}

main() {
  parse_mode "$@" || return
  require_root_environment || return
  capture_invocation_overrides || return
  if ! load_current_config; then
    current_config_load_guidance
    return 1
  fi

  case "${INSTALLER_MODE}" in
    install)
      require_interactive_tty || return
      collect_config_interactive install || return
      ;;
    update)
      require_existing_installation update || return
      adopt_current_config || return
      ;;
    reconfigure)
      require_interactive_tty || return
      require_existing_installation reconfigure || return
      collect_config_interactive reconfigure || return
      ;;
  esac

  validate_config || return
  execute_deployment || return
  print_completion_summary
}

if [[ "${INSTALLER_SOURCED}" != "true" ]]; then
  main "$@"
fi
