name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          corepack enable
          corepack prepare pnpm@8.15.9 --activate
          pnpm install --frozen-lockfile
        working-directory: frontend

      - name: Build
        run: pnpm build
        working-directory: frontend

      - name: Archive app artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist

  build:
    runs-on: ubuntu-latest
    needs: build_frontend
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]

    env:
      CGO_ENABLED: 0
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      GOARM: ${{ matrix.goarm }}

    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Checkout
        uses: actions/checkout@v4

      - name: Download app artifacts
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist

      - name: Build
        run: go build -o bupt-ec -v ./

      - name: Archive app artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bupt-ec
        path: bupt-ec
